### ISSUE TITLE
Terraform crashed when powered off existing "vsphere_virtual_machine" resource then apply again

### ISSUE THREAD

**Issue by Rocking80** [terraform-providers/terraform-provider-vsphere#134]
### Terraform Version
Terraform v0.10.1

### Affected Resource(s)
- terraform-provider-vsphere

### Terraform Configuration Files
```hcl
resource "vsphere_virtual_machine" "PengDemoRedhat65" {

    count = "${length(var.vms_address)}"

    datacenter = "DC"
    resource_pool = "/Resource_Pool"

    name = "${element(var.vms_name, count.index)}"
    dns_suffixes = "${var.dns_suffixes}"
    dns_servers  = "${var.dns_servers}"
    vcpu = "${element(var.vms_vcpu, count.index)}"
    memory = "${element(var.vms_memory, count.index)}"

    network_interface {
        label = "VM Network"
        ipv4_prefix_length = "22"
        ipv4_address = "${element(var.vms_address, count.index)}"
        ipv4_gateway = "${element(var.vms_gateway, count.index)}"
    }

    disk {
        datastore = "Automation"
        template = "Template_Redhat_6.5"
        type = "thin"
    }
}
```

### Debug Output
https://gist.github.com/Rocking80/758754e3837bc226a4c88c99327d7f9f

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
Sorry cannot provide the crash.log which contains lots of private information.

### Expected Behavior
The shutdown machine can be powered on at 2nd `terraform apply`

### Actual Behavior
terraform crashed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` succeeds and the vms are created on vcenter
2. shutdown one of remote vmware machine
3. `terraform apply` again

**Comment by vancluever** [comment]
Hey @Rocking80 - thanks for the bug report!

Judging from where in the code this is crashing, I think this should be fixed by #129. This will be landing in a new release tomorrow.

One thing that this does not necessarily address is the power state of a virtual machine - currently, the `vsphere_virtual_machine` resource does not manage power state, so the VM will not be turned on during the next apply, and more than likely you would see an empty diff.

I am going to leave this open so that we have this as a feature request. Be sure to update tomorrow when the next release comes out to fix the crashes however!

**Comment by Rocking80** [comment]
Thanks vancluever, you guys are awesome. Great job!

**Comment by krzkowalczyk** [comment]
@Rocking80 
Is apply working for you on powered off machine ?

I'm having an issue with executing plan command on powered off machine. When any on nodes included in state is powered off, terraform is crushing with error `unexpected EOF` for every machine. It's really annoying because you cannot validate all your resources by one command. With apply command to be honest i didn't check.

**Comment by vancluever** [comment]
Hey @krzkowalczyk - your specific issue should be fixed in more recent versions of the provider. Have you tried using TF v0.10.x and an updated version of the plugin? Let us know!

**Comment by krzkowalczyk** [comment]
So terraform v0.10.2 with vsphere provider 0.2.2 gives me an error while doing plan on powered off machine.
Here's [debug log](https://gist.github.com/krzkowalczyk/56211b6b1646c3ba8f84152deabaf37b)
A strange thing is that terraform doesn't crush on other vm which is powered off as well. This made me thinking and I did a short test. I've turned on the failing machine, run plan and it worked.I've turned off machine again, run plan and it worked. So right now everything works fine.
Anyway I will try to observe if terraform behaves properly on turned off machines.

**Comment by bpoland** [comment]
@krzkowalczyk if you look at the powered off VM in the vsphere client, does it still list an IP address?  It seems that VMware keeps the IP address populated for a time even after the VM gets powered off, and that allows terraform to proceed.

**Comment by vancluever** [comment]
Hey @Rocking80 - the pending power state work that I mentioned a few weeks ago is now in master, so this issue has auto-closed. It should be available in the next release.

@krzkowalczyk - I hope that issue isn't surfacing again :confused: but if it continues for you please send along the bug report in a new issue.

Thanks!
