### ISSUE TITLE
Customization does not work for windows 2008 R2 template 

### ISSUE THREAD

**Issue by Rocking80** [terraform-providers/terraform-provider-vsphere#140]
### Terraform Version
v0.10.1

### Affected Resource(s)
 - terraform-provider-vsphere

### Terraform Configuration Files
```hcl
resource "vsphere_virtual_machine" "TerraformSampleMachine" {

    count = "${length(var.vms_address)}"

    datacenter = "${var.datacenter}"
    resource_pool = "${var.resource_pool}"

    name = "${element(var.vms_name, count.index)}"
    dns_suffixes = "${var.dns_suffixes}"
    dns_servers  = "${var.dns_servers}"
    vcpu = "${element(var.vms_vcpu, count.index)}"
    memory = "${element(var.vms_memory, count.index)}"


    network_interface {
        label = "VM Network"
        ipv4_prefix_length = "22"
        ipv4_address = "${element(var.vms_address, count.index)}"
        ipv4_gateway = "${element(var.vms_gateway, count.index)}"
    }

    disk {
        datastore = "${var.datastore}"
        template = "${var.templates["windows_2008_R2"]}"
        type = "thin"
    }
}
```

### Debug Output
https://gist.github.com/Rocking80/e9f55a5b5403ca1a629c798ed9e1b5fb 

### Expected Behavior
The windows 2008 R2 machine should be created and configured correctly. And `terraform apply` finish successfully.

### Actual Behavior
The windows 2008 R2 machine is created but network for it (ip, gateway, DNS) and hostname is not configured. And `terraform apply` is always printing 'Still creating' without ending.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
From the vcenter console, we can see the vmware tasks are done without error. 
tasks are:
1. clone virtual machine
2. Reconfigure virtual machine
3. Reconfigure virtual machine
4. Customize virtual machine guest OS
5. Power on virtual machine

After all tasks are finished and wait for half an hour, I am trying to logon to the machine, there is message prompt to restart the machine. I restarted the machine manually and still does not work. 

The vmware tools are latest on the template machine.

Windows 2012 R2 does work.

Don't know if this is a terraform issue or a vmware API issue?

**Comment by vancluever** [comment]
Hey @Rocking80 - thanks for the report!

The best thing that will indicate whether or not this is a VMware tools issue or a TF issue is the customization logs - a couple of articles that might help:

[Sysprep log file locations](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2001932)
[Customization troubleshooting](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1026317) (note this one is for vCD but has log file locations in it that may exist)

There's a possiblity it could be a mix of both, but you can look and report on if anything stands out that would be great!

**Comment by Rocking80** [comment]
Thanks @vancluever for the response. Unfortunately I have no permission to operate on the vCenter so cannot see the customization logs. Do you have this kind of environment to have a try? Thanks.

**Comment by Rocking80** [comment]
@vancluever Could you please try this on your own environment?

**Comment by AndrewSav** [comment]
It feels that the Windows part of the provider requires some TLC. I'm having similar issues with Windows Server 2012 now. Basically, terraform cannot detect when the customization has finished. It leads to a number of other issues: provisioners trying to connect before customization completed, provisioners not being able to connect, because customization changed the ip address on the adapter and they are still trying to connect to the old one, etc.

I have a set of powercli scripts that do the provisioning they way I need, and I know that it is certainly possible to detect when customization if fully completed and of course using the correct ip address as configured on the network interface in the terraform configuration should be a no-brainer.

I wanted to migrate to terraform and standardize on it for most provisioning needs we have but with the current state of the vSphere provider (the Windows part) it proves impossible. It's good that these issues are being addressed and hopfully when it's fixed I'll be able to use it - terraform is really nice ;)

**Comment by jcaugust** [comment]
@AndrewSav, I was having a similar issue and am using [this](https://github.com/jcaugust/terraform/commit/87f2a86bc8e051cc70200edd8f156daec13de146) in my environment to wait for customization on windows. This was created before the Terraform provider split out. I'd be happy to create a PR if those maintaining the vsphere provider are interested.

**Comment by AndrewSav** [comment]
@jcaugust That's good to know, thank you for sharing. What about the ip address issues, did you have it? In my case if customization changes the network adapter settings terraform keeps trying to run a winrm provisioner on the old IP. Have you experienced that?

**Comment by jcaugust** [comment]
Yes. Without that patch, TF would try to run the provisioner before the VM had an IP address (which would fail).

**Comment by AndrewSav** [comment]
Ah, so the provisioner retrieves the ip address from the VM before trying to connect to the said VM. That makes sense. I for some reason thought that the ip is retrieved at the start and saved in a variable or something for provisioner to use.

**Comment by Rocking80** [comment]
@jcaugust Great to see you have those patch to solve the problem. Could you please make the necessary changes based on latest terraform-provider-vsphere code and create a pull request for that? So other guys can get the fix ASAP. Thanks.

**Comment by jcaugust** [comment]
Yes, I will do that once I upgrade my environment to TF 0.10.X and work through the provider split out.

**Comment by krzkowalczyk** [comment]
I've noticed following things on my environment running Vsphere 5.5
Windows 2008 R2
Retrieving ip address from DHCP works fine.
With static ip assigned it was retrieving apipa address on terraform < 0.9.0. Right now I didn't check as we have workaround to use a desired ip address in connection resource, so it doesn't rely on returned address.
Windows 20012
Retrieving ip address from DHCP returns apipa address. Static ip not tested because of workaround described earlier. As it was mentioned it seems that terraform doesn't wait for end of customization. But for some reason it works for 2008R2 in my case, and worked 2 times for 2012 (both templates are build with the same process using Packer)

**Comment by Rocking80** [comment]
Hi @krzkowalczyk , how do you use connection resource to set static ip for windows 2008 R2? Thanks.

**Comment by krzkowalczyk** [comment]
@Rocking80 
Assuming you provide an IP address for new host by variable `${element(var.vms_address, count.index)}` and you use it in network_interface block, then in connection block you don't need to retrieve ip address from terraform by: 
```
    connection {
      type     = "ssh"
      user     = "vagrant"
      host     = "${vsphere_virtual_machine.TerraformSampleMachine.network_interface.0.ipv4_address}"
      password = "vagrant"
    }
```
because ip address is already known in  `${element(var.vms_address, count.index)}`
so you can do:
```
    connection {
      type     = "ssh"
      user     = "vagrant"
      host     = "${element(var.vms_address, count.index)}"
      password = "vagrant"
    }
```
To make it simpler even, I wrote a wrapper script using ruby templates (which is wrapped by jenkins pipeline to provide input form) which generates .tf files with mostly hard coded values for parameters, including ip addresses so in my case tf file have explicitly stated IP.
The only case where we can't do it is when using DHCP as IP is not known before.

**Comment by vancluever** [comment]
Hey all! Sorry for the silence on this one, just wanted to make sure that I was able to take the time to give this one some attention.

So it looks like we definitely have an issue here. It probably stems from this:

```
2017-09-11T09:05:47.620-0700 [DEBUG] plugin.terraform-provider-vsphere_v0.2.2_x4: 2017/09/11 09:05:47 [DEBUG] VM customization starting
2017-09-11T09:05:50.573-0700 [DEBUG] plugin.terraform-provider-vsphere_v0.2.2_x4: 2017/09/11 09:05:50 [DEBUG] VM customization finished
```

That is the `CustomizeVM` call on a W2K16 template taking 3 seconds to return success. :confused:

Obviously, this is taking much longer than three seconds - about a couple of minutes for my test VM.

Looking into it, and obviously from what we've seen here, this is not a accurate way to wait for customization to complete. I have done a bit of research into it, and it looks like the correct way to do this is to watch for customization events, which can clearly be seen in the event log in vCenter.

govmomi has an events package that I'd imagine encapsulates the events part of the API. I don't know if there's a waiter, but TF itself has an API that we can use to wait for the event anyway, so that's not a big deal.

I think this is an easy win for us to make the VM resource better to work with without having to wait for the refactor (in addition, we will need this for the refactor anyway) so I will be prioritizing this one.

Cheers!

**Comment by AndrewSav** [comment]
@vancluever 

> I have done a bit of research into it, and it looks like the correct way to do this is to watch for customization events, which can clearly be seen in the event log in vCenter.

That's what I'm doing in my powershell/powercli script. It appears to work reliably.

**Comment by vancluever** [comment]
@AndrewSav indeed, and I have it functional on this end too. Funny enough switching this to an event waiter uncovered another bug with how we are waiting for guest net information, which I've fixed as well. I'm just working on tests, and we should have this merged in a few days tops!

**Comment by vancluever** [comment]
Hey all!

As the issue log here indicates, I've made some significant changes here that should fix this issue now:

 * Customization events are now the source of truth for customization completion, ensuring that a VM is not "created" until this part is fully reported as complete.
 * The behaviour of the network waiter has been significantly changed - we now wait for a _routeable_ address, it's no longer run on `Read`, but `Create` and `Update` instead, and can actually be completely disabled (if you have a config with NICs without a default route or no configuration at all).

The latter was needed as on my own config, after fixing the customization, there's a small moment after customization completes that VMware tools reports an auto-configuration address (169.254.x.x) before changing to the proper static configuration. This gets passed to the provisioner which obviously causes the provisioner to fail.

Anyway, we are bumping to 0.3.0 and will releasing shortly, so keep an eye out!
