### ISSUE TITLE
Windows 2012 customization does not finish in required by defaultAPITimeout time

### ISSUE THREAD

**Issue by krzkowalczyk** [terraform-providers/terraform-provider-vsphere#160]
Hi there,

After implementing PR [#158](https://github.com/terraform-providers/terraform-provider-vsphere/pull/158) we now check customization events to ensure the process has finished. Therefore in my test environment customization on win2012 takes more than 5min (which is set in defaultAPITimeout), and cause timeout error.

### Terraform Version
Terraform v0.10.5.

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files
```hcl
resource "vsphere_virtual_machine" "mwawposhck003" {
  name               = "mwawposhck003"
  folder             = "terraformtest/HEALTHCHECK/Development"
  annotation         = "HealthCheck 03 - Windows 2012 Standard"
  vcpu               = 6
  memory             = 8192
  datacenter         = "MyDataCenter"
  cluster            = "MyCluster"
  dns_suffixes       = ["mydomain.pl"]
  dns_servers        = ["192.168.1.6", "192.168.1.8"]
  time_zone          = 100
  skip_customization = false

  network_interface {
    label       = "VM Network 896"
  }

  disk {
    datastore = "Dell_MD/Dell_MD_Storage01"
    template  = "terraformtest/W2K12R2STDUAT"
    type      = "thin"
  }
}
```

### Debug Output
https://gist.github.com/krzkowalczyk/e8b71b209b860445cf89e287c44507e2

### Panic Output
https://gist.github.com/krzkowalczyk/e8b71b209b860445cf89e287c44507e2

### Expected Behavior
Terraform waits for end of customization.
`defaultAPITimeout` should be increased, or there is a new APITimeout parameter available to configure in resource.

### Actual Behavior
Terraform gets timeout after 5min.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
It takes some time and at least 2 reboots after powering on, until node ends customization.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- [GH-158](https://github.com/terraform-providers/terraform-provider-vsphere/pull/158)

**Comment by vancluever** [comment]
Hey @krzkowalczyk - thanks for sending this in. We actually do have a test for this (TestAccResourceVSphereVirtualMachine/windows_template,_customization_events_and_proper_IP) but possibly due to differences in our lab environments customization is actually running over for you (I think it takes about 3 or so mins on this side, so I'm not surprised).

As mentioned in #162 I'm working on increasing this timeout for customization only as I want to make sure we still maintain default timeouts for every other call that depends on the default timeout. The patch should be in soon!

**Comment by vancluever** [comment]
Hey @krzkowalczyk, this has landed in master - expect a release probably tonight or tomorrow. Thanks!
