### ISSUE TITLE
panic: reflect.Set: value of type mo.DistributedVirtualSwitch is not assignable to type mo.VmwareDistributedVirtualSwitch

### ISSUE THREAD

**Issue by hlima** [terraform-providers/terraform-provider-vsphere#161]
terraform crashes with the message above if using a specific network label. Using the standard "VM Network"  label works fine.

### Terraform Version
Terraform v0.10.5

Vsphere plugin version:
 terraform providers
.
└── provider.vsphere ~> 0.3

### Affected Resource(s)

- vsphere_virtual_machine

### Terraform Configuration Files
```hcl
provider "vsphere" {
  user           = "myuser"
  password       = "mypassword"
  vsphere_server = "myurl.com"
  version = "~> 0.3"
  # if you have a self-signed cert
  allow_unverified_ssl = true
}

resource "vsphere_virtual_machine" "web" {
  name   = "terraform-web"
  vcpu   = 2
  memory = 4096
  cluster = "mycluster"
  network_interface {
    label = "mynet"                   
    ipv4_address = "192.168.11.160"
    ipv4_prefix_length="24"
    ipv4_gateway = "192.168.11.1"
  }

  disk {
    datastore = "mydatastore"
    template = "mytemplate"
  }

}

```

### Debug Output
https://gist.github.com/hlima/b6931ad3347fcf1e313dc4ec8b0bd25c#file-debug-output

### Panic Output
https://gist.github.com/hlima/0edaca6f7b7774fcafcd4a3c24a696ce
### Expected Behavior

Specified a network label. Expected the VM to be created and assign to that network.

### Actual Behavior

terraform crashed.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Using a  network label that maps into a  VmwaRE Distributed Virtual switch ( vcenter tags as VmwareDistributedVirtualSwitch) casuses the crash. Using the standard "VM Network" label things work fine
Trying to create a VM with the same network label using govc also crashes with similar  output

**Comment by vancluever** [comment]
Hey @hlima, thanks for the report and sorry you are having trouble!

I've been doing a bit of investigation on this end and I am having issues trying to force the creation of a vSwitch that will get the non-VMware `DistributedVirtualSwitch` type. I'm guessing this is because this is possibly an object type that's reserved for 3rd party vSwtiches, but I'm not too sure. But given this I think it's worth asking if the network in question is backed by one?

This would be a vSwitch that is supplied by a 3rd party piece of hardware. Found a bit of info here that might be relevant: https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2149722

If you can let us know that would be great - and in the meantime we will pass this up to VMware to see if they can help re-produce.

Thanks!

**Comment by hlima** [comment]
@vancluever 
The network in question is backed by a Cisco Nexus 1000V

**Comment by vancluever** [comment]
@hlima awesome. I think this is our issue then for sure. :+1:

Waiting on vmware/govmomi#845 which should fix this.
