### ISSUE TITLE
Data Sources and Provider cannot be used together

### ISSUE THREAD

**Issue by vernak2539** [terraform-providers/terraform-provider-vsphere#216]
It looks as if the vSphere data sources and the provider do not work together. The Data Sources require you to provide a name and then return an ID. 

The provider doesn't allow use of IDs when configuring the `vsphere_virtual_machine` resource. It only uses name. This essentially makes the Data Sources unusable or irrelevant.

The API allows for IDs to be passed for configuration. Is there a way to allow this?

### Terraform Version

`Terraform v0.10.7`

### vSphere Provider Version

`provider.vsphere ~> 0.4`

### Affected Resource(s)

- `vsphere_virtual_machine`

I believe this may affect other resources as well

### Terraform Configuration Files

https://gist.github.com/vernak2539/fa38744a2f4428a8a785bc67f45c7846

### Debug Output

Message stating it cannot find the datacenter with the provided id fetched from the data source

### Panic Output

N/A

### Expected Behavior

I expected to be able to use the ID provide via the Data Source to configure the `vsphere_virtual_machine` resource

### Actual Behavior

The `vsphere_virtual_machine` resource relies on names, not id's to configure a VM. 

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan` -- will work
2. `terraform apply` -- will fail with error

**Comment by vancluever** [comment]
Hey @vernak2539. The `vsphere_virtual_machine` provider is undergoing a large refactor to better support the new data sources that have been added over the last few months. You are right in that the VM resource currently does not support them, but the vast majority of the other resources that have been set up since then (namely having to do with networking, data storage, and inventory) do support them. Other, older, resources will be refactored soon as well.

So for now, using the name is the correct way to do this, but this will be changing soon as we hit a v1.0.0 release on the provider.

Thanks!
