### ISSUE TITLE
Custom_configuration_parameters is ignored!!

### ISSUE THREAD

**Issue by tommymunter** [terraform-providers/terraform-provider-vsphere#230]
Hi there,

I try to use "custom_configuration_parameters" to set values.
Guest os, to start with. But nothing is actually set on vsphere_virtual_machine.
I would like to set:
guest os
vm version
device boot order
vm autostart order
and more on...
All I do manually should be possible to configure?!?!

### Terraform Version
Terraform v0.10.7

### vSphere Provider Version
v 0.4.2

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
  disk {
   datastore = "${var.vmdatastore}"
   size = 10
   type = "thin"
   name = "disk"
   bootable = true
  }
 skip_customization = true
 custom_configuration_parameters {
  "guestOS" = "centos64Guest"
 }
```
### Expected Behavior

New "vsphere_virtual_machine" should get parameters I set!

### Actual Behavior
New "vsphere_virtual_machine" only gets default parameters.

Other Linux (64-bit)

Then after pxe install is finished, guest OS is changed to correct value to Centos 7
### Steps to Reproduce

terraform apply

### Important Factoids
VMware ESXi 6.0.0 Build 3620759

**Comment by jason-azze** [comment]
It looks like you have `skip_customziation = true`, so I wouldn't expect there to be any customization step at all.

**Comment by tommymunter** [comment]
Hi
I changed to `skip_customziation = false`, then it got even worse. Ignoring **custom_configuration_parameters** and after VM is installed still holds to **Other Linux (64-bit)**.

**Comment by vancluever** [comment]
Hey @tommymunter, there are, unfortunately, a number of things that are currently not supported in the VM resource, including a number of items you have mentioned. We are currently working on a new version that will help address a number of those issues (and we are actually testing with a PXE image).

Out of the features that you have listed, we will be in the v1.0.0 release supporting guest OS customization. The other features may follow depending on demand, feasibility, and available cycles to implement (VM version may be the easiest to implement out of the items that you have otherwise listed).

We hope to have the new version of the resource out by the end of the month, so keep an eye out!

**Comment by rismoney** [comment]
Do you have any indication on breaking changes or is it fully compatible w latest provider version semantics?   Terraform can get quite nasty with forced resource changes.
