### ISSUE TITLE
Receive unauthorized error intermittently 

### ISSUE THREAD

**Issue by deberon** [terraform-providers/terraform-provider-vsphere#239]
### Terraform Version

0.10.8

### vSphere Provider Version

0.4.2

### Affected Resource(s)

* vsphere_folder

### Terraform Configuration Files

```hcl
resource "vsphere_folder" "env" {
    path = "${var.environment}"
    datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
    type = "vm"
}
```

### Debug Output

Will provide if needed

### Panic Output

N/A

### Expected Behavior

Resource is created without issue

### Actual Behavior

I receive the following error when trying to create a resource in vsphere:

```vsphere_folder.env: Creating...
  datacenter_id: "" => "datacenter-21"
  path:          "" => "dev"
  type:          "" => "vm"

Error: Error applying plan:

1 error(s) occurred:

* vsphere_folder.env: 1 error(s) occurred:

* vsphere_folder.env: error reading tags: Get unexpected status code: 403: call failed: Error response from vCloud Suite API: {"value":{"messages":[]},"type":"com.vmware.vapi.std.errors.unauthorized"}```

After clearing out all the sessions for the user, and re-running the job it completes without error.

### Steps to Reproduce

1. Create admin user in vsphere
2. `terraform apply`

### Important Factoids

vCenter Server v6.0.0

**Comment by vancluever** [comment]
Hey @deberon, are you using this with a user that does not have access to tags?

If so, can you try giving this user access to tags and then try again? Just looking at the output it seems like this is the source of the issue.

Thanks!

**Comment by deberon** [comment]
@vancluever I created a role in vsphere called "Terraform Admin" that, for testing purposes, has all privileges enabled. The problem appears to be intermittent and is usually remedied by me clearing all the sessions and running the apply again.

**Comment by deberon** [comment]
I recently had a bug here: https://github.com/terraform-providers/terraform-provider-vsphere/issues/194 where I received the same error. Adding permissions for tags seemed to resolve it for a while but maybe I just got lucky during the testing and the error didn't manifest.

**Comment by vancluever** [comment]
Ahh, hah! Hello again @deberon!

I remember that issue after reading up. Do you make sure to do a full session flush after clearing out permissions? It might even be a good idea to do it under a different user (if you aren't already).

I can definitely confirm that vSphere does hold on to those sessions, as frustrating as it is :confused:

Is it possible that you were using a different user for testing from what you use for production provisioning as well?

PS: The documentation clarification will be coming ahead of our big release later this month. Sorry if it's been an ongoing source of confusion on this!

**Comment by deberon** [comment]
Yeah I flushed all the sessions many times and haven't changed permissions in a few weeks (made this dev environment use an admin account for testing). I just ran a job that failed with the above error and immediately ran an apply after (without flushing sessions) and the folder was created successfully. Makes me think it might be a race condition? But now I'm just guessing. Hopefully this helps.

Do you know if there is anything coming up in the v1 release that might address this? Or if there is a branch I could compile to test it myself?

**Comment by vancluever** [comment]
@deberon I can confirm we aren't doing anything to tags that isn't already in for v1.0.0, and in all honesty I can't think of what could be the issue here at this point in time (not saying that there isn't one). We use VIC's [tagging package](https://github.com/vmware/vic/tree/master/pkg/vsphere/tags) to manage tags, so we are not using a local implementation either.

The only thing I could think of is maybe to engage VMware support on this and see if they can help track down the source of the intermittent issues. In the meantime, I will leave this open as a note to review our tests and see if there's anything we've missed. I've also just run our folder and tags acceptance test suites against our vSphere Lab (6.5U1), and all have passed. If you are so inclined, you can see what we are covering in acceptance tests at the following links: [folder](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_folder_test.go), [tag](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_tag_test.go), and [tag category](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_tag_category_test.go).

Sorry this is causing you so much trouble and I will update when I have more info!

**Comment by deberon** [comment]
@vancluever thanks! I appreciate the attention you've given this. I'll try to replicate these issues in another vsphere environment we have.

**Comment by deberon** [comment]
Sorry for the long delay, but I finally got around to attempting to create a folder in a different vmware environment and received the same error. The folder gets created properly and when I run an apply (without making any other changes) it continues as normal.

**Comment by Jereom** [comment]
Hi, I have exactly the same behavior, with the same error message, vSphere v6.0.0.
Any progress, or a way to avoid/catch the error?

**Comment by deberon** [comment]
I have not found a work around for this but I have also stopped looking for one. We just run a terraform apply again and everything continues working as expected.

**Comment by AndrewSav** [comment]
I have the same error, run under user that have all the privileges and I'm getting this error consistently if the  folder to create is absent. There is no error when you re-run it and the folder is already there. If you delete the folder and re-run from scratch the error is back.

**Comment by bill-rich** [comment]
Hi All. I'm going to close this issue as it is likely resolved with the addition of [persist_session](https://www.terraform.io/docs/providers/vsphere/index.html#persist_session). If the problem still exists, we can reopen the issue.
