### ISSUE TITLE
Trying to upgrade from 0.4.2 to 1.03 

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#287]
Hi there,

### Terraform Version

Terraform v0.10.7

### vSphere Provider Version

1.03

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

I had a simplistic module design in 0.4.2 where I had a single vsphere_virtual machine resource within the module, that I invoked.  The module contained this:
  ```
disk {
    template = "${var.template}"
}
```

The problem I am having now is that this seems to now be passed in via template_uuid within a clone stanza, and I receive this error now:

* module.rismoneyhost.vsphere_virtual_machine.wks: this resource was imported or migrated from a previous version and does not support cloning. Please remove the "clone" block from its configuration
* module.rismoneyhost.vsphere_virtual_machine.wks: 1 error(s) occurred:

I am not sure how to work around this.

**Comment by vancluever** [comment]
Hey @rismoney, for the configurations that you are migrating, you will need to remove the `clone` block from your configuration. This is a safeguard to ensure that someone doesn't accidentally delete their VMs when migrating, as all attributes in the `clone` and `customize` sub-resources are force new resources.

We may look at fixing this in future releases, but due to complexity of the sub-resource and the number of options contained within, this might not be avoidable.

Note that this does not apply to new resources - the flag that blocks this is only applied when a resource is migrated from a <= 0.4.x resource, or imported. New VMs will create just fine.

Hope this helps!
