### ISSUE TITLE
Support for Template Deployment from VMWare Content Library

### ISSUE THREAD

**Issue by steffencircle** [terraform-providers/terraform-provider-vsphere#291]
Hi there,

### Terraform Version
> terraform -v
Terraform v0.11.1
+ provider.vsphere v1.1.0

I am trying to deploy a Virtual Machine from a Template that sits on a VMWare Content Library.
This is a feature from VSphere 6.0 onwards.

Unfortunately the provider seems to be not able to find a Template from it.

I get the following error, when a specify a VM Template from it.

_Error: Error refreshing state: 1 error(s) occurred:

* data.vsphere_virtual_machine.template: 1 error(s) occurred:

* data.vsphere_virtual_machine.template: data.vsphere_virtual_machine.template: error fetching virtual machine: vm 'My-CL-TestTemplate' not found_

**Comment by danthedapperman** [comment]
I would love to see this, too :-)  Since libraries can be local or remote, supporting both is good

**Comment by seanmalloy** [comment]
I would love to see this too!

**Comment by seanmalloy** [comment]
It looks like govmomi does not support content library yet.

https://github.com/vmware/govmomi/issues/735

**Comment by antaln** [comment]
I'm interested in this too.

**Comment by antaln** [comment]
Content libraries use a vSphere automation API. Govmomi does not contain go bindings for the automation API.

Current workflow for cloning in terraform-vsphere is to match the disk specs in the resource with the one from the template, presumably because otherwise they are not recorded in the tfstate and subsequent apply will try to delete those disks. Getting existing specs from a template relies on virtual machine datasource.

For content libraries, the source of the template is an ovf item in the content library. Ovf file contains disk information in the disk section. So it seems at the very least we'd need a new data source for the ovf (and probably for content library and content library items), which would download the ovf, parse the section entries and make them available for use in defining disk specs for target virtual machine resource.

**Comment by antaln** [comment]
Customization options as used currently are not applicable to deploy-from-OVF. OVF may have own customization parameters, but that's entirely up to the OVF author. So, the OVF data source would need to also make list of customization parameters available, values of which can be set in a map in the clone/customize section.

Storage mapping during OVF deployment is only available if vmw:StorageGroupSection is available in OVF. This section is a vmware extension, not part of the OVF spec. If section is not defined, one can specify a default that applies to all disks in the OVF.

**Comment by bagusajah** [comment]
Hi, any update on this, or maybe refference for terraform to find template inside content libarary?

**Comment by Outek** [comment]
It would be very useful, to deploy images directly into the content library.

**Comment by cathode911** [comment]
https://github.com/vmware/govmomi/issues/735#issuecomment-417989573

finally there are plans to include content library bindings, hope it will be done soon

**Comment by bcornils** [comment]
Being this is such a popular request, we'd like to add it to our v2.0 milestone. During the v2.0 time, we will create an RFC to break out the work for this group to follow. Please let me know if you have questions or concerns.

**Comment by pathcl** [comment]
I think there's support already in govmomi https://github.com/vmware/govmomi/pull/1377

**Comment by pfreed** [comment]
Any updates on when this wil be available? And is there any workaround?

**Comment by SteDevFoss** [comment]
👍  This function is really interesting.

**Comment by scott1138** [comment]
Any movement on this?  It's not stopping us from using Terraform but it's a pretty big headache.

**Comment by thejharvey** [comment]
I'm hoping this is supported soon as well.

**Comment by RodrigoEmiliano** [comment]
Any updates on this?

**Comment by ausafonly** [comment]
Is there any update on this to include content library to deploy VM's

**Comment by nmaludy** [comment]
As someone who has to support multi-vsphere environments, i would LOVE to see this supported.

We routinely create a template in a Content Library and share that Content Library between vSpheres. This way we can have one "gold" template and all of the other vSpheres automatically get updates when that template is changed.

:+1:

**Comment by ooOOJavaOOoo** [comment]
Haven't checked on this in at least a year.  GOVOMI has been updated to support this, does anyone have the time to look at this?

**Comment by aareet** [comment]
Hi folks, thank you for all your comments - we've definitely registered all the interest in this feature and are looking into the effort it would require to implement so we can plan it in.

**Comment by ooOOJavaOOoo** [comment]
Checking back on this again.  Is there a workaround I can use?  This feature has officially hit a blocking point for us.

**Comment by ooOOJavaOOoo** [comment]
Temp solution - provision all VMs in Azure, hopefully this will come around soon.

**Comment by bill-rich** [comment]
I've been back on looking at how best to implement content library support and was hoping to get some feedback. The idea is that there will be a resource and data source for content libraries and content library items, but I'm unsure of the best way to implement deploying content library items. 

We could add the functionality into the existing virtual machine resource, but certain things like network mappings do not really fit into the existing schema. If we made a network mapping attribute, it would need to conflict with existing networks and would result in users not being able to add or remove networks from the virtual machine, or we would need to add a lot of complexity to make the two work together. 

Another option would be to have a separate resource for deployed content library items that are much simpler than virtual machines, and do not allow customization. This seems clunky since users would expect to be able to use them like other virtual machines. The upside would be users could create a deployed content library item and then use that as a source to clone standard virtual machine resources from. 

Any feedback on additional ideas or more info on what people's specific use cases are would be helpful.

**Comment by antaln** [comment]
Existing virtual machine resource already supports network change for a NIC, so I don't see why you'd need to worry about that in the initial deployment. You only need to make sure that:
- you apply any post-deploy customization after cloning/deploying from OVF,
- you can get information about the expected NIC config from the OVF you are deploying.

Same applies to any OVF properties - they take effect only when the VM is powered on, so AFAIK they can be applied after cloning/deployment using existing mechanisms (specifically, vsphere_virtual_machine.vapp.properties).

The datastore mapping is a different problem, since that cannot be changed post-deployment. Handling that is a little fuzzier:
- deploy endpoint provides a way to specify default datastore, which can map to existing
vsphere.virtual_machine.datastore_id. Not sure how it plays with datatore_cluster_id, though.
- specifying the mapping requires somewhat exotic vmware-specific OVF attributes, which are often not defined in OVFs.

My use cases are identical to cloning from template: ability to go from a content-library template to a VM with feature parity with existing clone-from-template: ability to specify networks, datastores, cpu, memory, OS customization options, etc.

The preferred way (to me) would be to be able to specify a content-library item UUID in the vsphere_virtual_machine.clone.template_uuid, and if the UUID maps to a content library item, issue a vcenter.deploy. That way there is less friction (no need to have two conflicting properties that you need to handle).

As for getting the VM configuration from the OVF, a new OvfItem datasource (inputs: (mandatory) item name, (optional) library uuid) could expose same attributes as a vsphere_virtual_machine datasource (disk, network_interface, memory, guest_id, num_cpus) but obtains them by downloading the OVF from the content library and parsing it (AFAIK, govmomi already contains the full OVF un/marshaller). This datasource should also expose OVF user-definable properties, preferably in a way that can be easily translated to vApp.properties. This avoids having to get these manually from the OVF (which takes a fair number of steps from UI) or try to infer them from the deployment UI (which shows display-friendly names). The workflow would be to set OvfItem datasource, then do a terraform apply and terraform show to get the vApp.properties entries.

**Comment by thefactor82** [comment]
No news about this feature? :-(
Also for us this feature has officially hit a blocking point...

**Comment by pillarsdotnet** [comment]
We had to switch away from Terraform and start using the underlying `govc` binary.

**Comment by ooOOJavaOOoo** [comment]
We've redoing our templates in Ansible, I think this feature may have taken too long and lost a huge market.

**Comment by ephos** [comment]
> No news about this feature? :-(
> Also for us this feature has officially hit a blocking point...

We are hitting that point as well for a huge number of use cases.  Some traction on this would be great.

**Comment by bill-rich** [comment]
Sorry everyone for how long it has taken to get this addressed. We have been working out the best way to implement this. It is very high on the backlog, and I expect to have some progress on adding content library support in the next few weeks. I will keep the community updated on status.

**Comment by thefactor82** [comment]
Just to give a little "traction" to this case after a month... I don't want to bother anyone, just let you know that I really really really waiting for this!

**Comment by bill-rich** [comment]
This feature will be released very soon. We're just in the final steps to make sure we're covering primary use cases as well as possible.

**Comment by Satak** [comment]
This is great news that you are adding support for content library. I think this is also solves our storage policy id problem with datastores: https://github.com/terraform-providers/terraform-provider-vsphere/issues/991

Any ETA of merging that PR?
