### ISSUE TITLE
time_zone on vsphere virtual machine windows 1.1.0 

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#292]
before: vsphere complains the time zone is not a valid setting.

`time_zone = "035"`

configuration does not work if the leading 0 is provided.  ie 035 does not work, while 35 does.  

this works:
`time_zone = "35"`

documentation provides reference to MSFT indices for this value.

Thoughts for resolution:
Leading zero should be managed properly in code, or documentation should advise to omit leading 0's.

**Comment by rismoney** [comment]
As a further update to this,

If I set the configuration to `time_zone = "35"` and terraform apply, subsequent terraform plans show this as `"29"` which is problematic for many reasons, and is a breaking change holding up pipelines.

1.  This value is not even valid.  Not sure where it gets this from.
1.  This FNR

**Comment by vancluever** [comment]
@rismoney coincidentally `29` is the decimal form of octal `035`. Are you sure your configs don't have the leading zero in them?

We aren't reading this value back into state, so this has to be coming from config. I'm just reviewing the old code to confirm, but it's possible that this needs to be an octal value and that's why the leading zeros appear in the MS spec.

Changing this to a bug as there appears to be something up here for sure.

**Comment by vancluever** [comment]
@rismoney this is definitely an octal value. What I will do is "restore" the old functionality so that this is a string field that expects a number beginning with a leading zero so that it can be properly converted.

**Comment by vancluever** [comment]
@rismoney confirming that `85` (decimal) is actually UTC. Going to try another zero-padded zone in decimal form (removing the zero), and a non-zero padded one, and will post results.

**Comment by vancluever** [comment]
OK, results of test:

* Using `20` for Central Time is functional
* Using `215` for Singapore Standard Time is functional

So I don't think it's using octal, the values are just (tragically) documented with a leading zero in some cases. Moving this back to doc so that it gets documented in the resource documentation correctly.

**Comment by rismoney** [comment]
The config I use now on new provider 1.0.3 provider was `time_zone="35"`.  Terraform does not complain about this, but if I pass 035.

However using "35" then subsequent terraform plan returns this to be "29" and wants to FNR.

The config I used in 0.4.2 worked fine as "035" on old (unrelated resources)  resources.  

I'm thinking it's not doc, but rather octal handling, perhaps on the reading of the value.

```
clone.0.customize.0.windows_options.0.time_zone:           "35" => "29" (forces new resource)
```

**Comment by rismoney** [comment]
I am not able to repro this issue on the last few provider versions, so I am going to close at this time.

**Comment by vancluever** [comment]
Thanks @rismoney, if it does become an issue again at least we have a paper trail to help with documentation.
