### ISSUE TITLE
cdrom issue for managing a 0.4.2 host with 1.1.0

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#300]
If cdrom = "1" on existing image has nothing inserted, how can this be represented in TF code?

According to doc: both datastore and path are required attributes on the cdrom resource.  Can they be null?

**Comment by vancluever** [comment]
Hey @rismoney, currently CDROM drives need to have something in them or be removed. If the drive had nothing in it before then it will be updated the new specified parameters on the next run.

I'll add this as an enhancement as I could see scenarios where just ejecting the ISO would be favourable to hot-removing and adding the device.

**Comment by jason-azze** [comment]
@rismoney I was able to add a cdrom with path set to `""`.
I have:
```
  cdrom {
    datastore_id = "${data.vsphere_datastore.iso-datastore.id}"
    path         = "${var.iso_path}"
  }
```
and then I set `iso_path = ""` and it seems to work.
```
  ~ module.windows-build.vsphere_virtual_machine.windows[0]
      cdrom.#:              "0" => "1"
      cdrom.0.datastore_id: "" => "datastore-260"
```
I ended up with a CD/DVD device with just the datastore name in its target.
![cdrom-with-datastore-only](https://user-images.githubusercontent.com/1788669/34961788-c18b200a-fa0e-11e7-8268-f26aa109d761.png)

I did have to power off the VMs before applying the plan because...
```
vsphere_virtual_machine.windows.0: error reconfiguring virtual machine: The attempted operation cannot be performed in the current state (Powered on).
```
@vancluever I was about to open an issue about the power state when adding a cdrom and came across this issue in my research. Is there value in creating an issue about a successful plan to add a cdrom that can't be applied without changing the power state of the VMs outside of TF?

**Comment by vancluever** [comment]
Hey @jason-azze, are you saying that CDROM operations require restarts?

If that's the case then that might be able to be fixed for sure and I think it's issue worthy :slightly_smiling_face:

**Comment by rismoney** [comment]
I think this can be closed @vancluever - not having any cdrom issues anymore, and can re-open if needed.

**Comment by vancluever** [comment]
Hey @rismoney, we are actually working on this issue and others related to CDROM management - we haven't forgotten about it! Keep an eye out for a PR soon.

**Comment by bill-rich** [comment]
Hi @rismoney, we've added the ability to have a CDROM mapped to a client device (instead of an ISO) in #421. Now, if you'd like a CDROM with nothing inserted, you can remove `path` and `datastore_id`, and instead set `client_device` to `true`. Please see the [new docs](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/website/docs/r/virtual_machine.html.markdown#cdrom-options) for more details.

@jason-azze As part of the changes to support client CDROM devices, some additional checks were added to make sure all the necessary config parameters are provided and none are in conflict. This additional validation will affect your ability to pass an empty string for `path`. I'm sorry about any inconvenience it may cause. Switching over to using `client_device` instead of an empty `path` will work with this new feature.

**Comment by rismoney** [comment]
Excellent and kudosnto you guys doing awesome work on TF!  Your hard work is noticed and appreciated
