### ISSUE TITLE
Ability to define multiple scsi controllers with different types

### ISSUE THREAD

**Issue by dannyk81** [terraform-providers/terraform-provider-vsphere#310]
### Terraform Version
`Terraform v0.11.1`

### vSphere Provider Version
`provider.vsphere v1.1.0`

### Affected Resource(s)
- `vsphere_virtual_machine`

### Expected Behavior
Be able to specify the scsi controller type per disk

### Actual Behavior
`scsi_type` parameter is a general parameter per VM and all controllers created on this VM will be of the same type.

### Important Factoids

We are deploying VMs that are used for Database nodes, the data is stored on a dedicated virtual disk and we would like to use pvscsi controllers to improve IO perfromance and reduce CPU overhead, however it is quite a headache to use pvscsi for Boot OS virtual disk (in fact it's not supported for Debian OS that we use, though may be possible).

Today we manually define two scsi controllers, the first is lsi_logic for the boot os virtual disk and the 2nd is of type pvscsi for the data virtual disk.

Currently, it seems impossible to implement the above configuration with Terraform and the vsphere provider.

**Comment by vancluever** [comment]
Hey @dannyk81, sorry you are experiencing trouble.

The decision to use a single SCSI controller type for the entire virtual machine was a deliberate decision to simplify device management across all virtual disks. Hence, this something that we will not be supporting any time soon.

FWIW, when we made the decision to use PVSCSI as the default controller type, I did check to see what kind of support the drivers had. The SCSI driver has been mainline since 2009, which is now a period of 8 years. You can see the list and dates [here](https://kb.vmware.com/s/article/2073804). It's been in Ubuntu since 2010, but it may not have made it into Debian Squeeze (which was released a little under a year later) due to it being off by a single patch version (2.6.32 vs 2.6.33). I'd imagine Wheezy should definitely have it as it is a 3.x kernel. Squeeze is also EOL, so we can't reasonably support it.

Going to close this now as there is nothing that is going to be actionable here. We may come back to this in the future, but there are currently no plans.

Thanks!

**Comment by dannyk81** [comment]
Thanks for the clarifications! we are going to make an attempt to use pvscsi for boot, hoping for the best 😄
