### ISSUE TITLE
Terraform - timeout waiting for customization to complete

### ISSUE THREAD

**Issue by alexholliz** [terraform-providers/terraform-provider-vsphere#312]
### vSphere Provider Version

`Terraform v0.11.1`
`+ provider.vsphere v1.1.0`

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine.vm`

### Terraform Configuration Files

```hcl
##terraform file

provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "Replaced for anonymity"
}

data "vsphere_datastore" "datastore" {
  name          = "sf-vmware-04"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "dportgroup-server-vlan-16"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "centos-7-template"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name          = "it-docker-prod-01"
  datastore_id  = "${data.vsphere_datastore.datastore.id}"

  num_cpus      = 2
  memory        = 4096
  guest_id      = "centos64Guest"

  network_interface {
    network_id  = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    name        = "it-docker-prod-01.vmdk"
    size        = "${data.vsphere_virtual_machine.template.disks.0.size}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"


    customize {
        network_interface {
          ipv4_address  = "172.16.16.140"
          ipv4_netmask  = "24"
        }

    ipv4_gateway        = "172.16.16.1"
    dns_server_list     = ["172.16.16.16", "172.16.16.17", "172.16.16.18"]
    dns_suffix_list     = ["Replaced for anonymity.com"]

        linux_options {
          host_name     = "it-docker-prod-01"
          domain        = "Replaced for anonymity.com"
        }

    }
  }

}

##Variable file

variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}

##Secrets File
vsphere_user = "DOMAIN\\User"
vsphere_password = "Password"
vsphere_server = "vcenter.replacedForAnonymity.com"
```

### Expected Behavior

Terraform Apply should have spun up the VM and customized it from the template

### Actual Behavior

The VM hung on first boot, this process runs indefinitely:
`A start job is running for dev-mapper-centos\x2droot.device`

### Steps to Reproduce
1. `terraform apply`

**Comment by RyanD0001** [comment]
Hi Vancluever is there any way of delaying the customisation as it seems to run before the vm is turned on?

**Comment by vancluever** [comment]
Hey all, sorry for the delay in replying to this one.

@alexholliz your issue sounds like an issue with the VM itself, in order to figure out what is going on you will need to look at the server itself. You can check the logs at the locations documented [here](https://kb.vmware.com/s/article/1026317) (note the article applies to vCloud Director but as mentioned in the article, the same process applies to vSphere). The `A start job is running for dev-mapper-centos\x2droot.device` sounds like something is going on with the disk though - you might want to see #323 which kind of describes a similar issue.

@RyanD0001 I think there's some confusion here - `CustomizeVM_Task` (the API call that you are seeing) is supposed to run when the VM is powered off, but that's only queuing up the customization for the next boot. So what you are seeing is normal. The actual guest-level customization happens within VMware Tools on the next boot after the customization spec is sent.

Let me know if those solves the pertinent problems/answers the relevant questions!

**Comment by RyanD0001** [comment]
Hi @vancluever thanks for your response, I just found my issue, it was down to a registry setting and sysprep.

Thanks

**Comment by vancluever** [comment]
Awesome - thanks for updating this @RyanD0001!

**Comment by vancluever** [comment]
Hey all, closing this now as it's been a few days - if there is a problem with what has been mentioned here feel free to open a new issue with the pertinent details.

Thanks!

**Comment by alexholliz** [comment]
I followed the recommendations in https://github.com/terraform-providers/terraform-provider-vsphere/issues/323 and defining the scsi device fixed the problem. This can remain closed!

**Comment by NZenitram** [comment]
@RyanD0001 Can you please elaborate on your registry setting and sysprep solution?
