### ISSUE TITLE
Cannot provision VM w/o resource_pool_id

### ISSUE THREAD

**Issue by ntrvic** [terraform-providers/terraform-provider-vsphere#314]
Hello,

I was using vsphere provider 0.4 and just tried to update. One big problem is that our vsphere setup does not use resource pools of any sort. I have scanned through the docs, and one section mentions 
```
If you don't have any resource pools in your cluster, or you want to use the parent resource pool for a cluster, you can just specify the Resources named default in your path for the resource pool:
```
However, I am no longer able to provision vms. I tried defining a default RP with cluster name/uuid, but no luck. Please advise. Is this intended behavior?

Thanks,
Victor

Terraform v0.11.0
+ provider.vsphere v1.1.0

**Comment by jason-azze** [comment]
Hi @ntrvic . I believe that `resource_pool_id` is required.

I have a vSphere lab environment with no defined resource pools, and my codes contains:

A datasource:
```
data "vsphere_resource_pool" "target-resource-pool" {
  name          = "${var.vm_cluster_name}/Resources/${var.resource_pool_designator}"
  datacenter_id = "${data.vsphere_datacenter.target-datacenter.id}"
}
```
And a `resource_pool_id` (required by the Terraform resource)
```
resource "vsphere_virtual_machine" "generic" {
  name             = "${var.name_prefix}${format("%02d", count.index + var.name_starting_val)}"
  resource_pool_id = "${data.vsphere_resource_pool.target-resource-pool.id}"
  datastore_id     = "${data.vsphere_datastore.target-datastore.id}"
```
Because I don't have a resource pool, I set the value of my variable `resource_pool_designator` to empty.
In my variables.tf
```
variable "resource_pool_designator" {
  description = "The name or path for the resource pool in which to create the resources"
}
```

And then in my tfvars file used at runtime:

```
resource_pool_designator = ""
```
So the `name` of my datasource gets interpolated to something like:
```
MyCluster/Resources/
```

**Comment by ntrvic** [comment]
Thanks! That helped me get passed.
