### ISSUE TITLE
OpenBSD guest IP detection

### ISSUE THREAD

**Issue by braddeicide** [terraform-providers/terraform-provider-vsphere#337]
OpenBSD vmware tools doesn't export routes so it never satisfies the WaitForGuestNet.  
I set wait_for_guest_net_timeout = 0 to get passed that.

The host ip is never populated now though:

vsphere_virtual_machine.tf (remote-exec): Connecting to remote host via SSH...
vsphere_virtual_machine.tf (remote-exec):   Host:
vsphere_virtual_machine.tf (remote-exec):   User: vagrant
vsphere_virtual_machine.tf (remote-exec):   Password: true
vsphere_virtual_machine.tf (remote-exec):   Private key: false
vsphere_virtual_machine.tf (remote-exec):   SSH Agent: false

vcenter shows the correct IP for the host.

It looks like vsphere/virtual_machine_guest_structure.go relies on more things that aren't exported, like PrefixLength.

terraform -v
Terraform v0.11.1
+ provider.vsphere v1.1.1

Guest info exported in https://github.com/openbsd/src/blob/master/sys/dev/pv/vmt.c
/* VM guest info keys */
#define VM_GUEST_INFO_DNS_NAME		1
#define VM_GUEST_INFO_IP_ADDRESS	2
#define VM_GUEST_INFO_DISK_FREE_SPACE	3
#define VM_GUEST_INFO_BUILD_NUMBER	4
#define VM_GUEST_INFO_OS_NAME_FULL	5
#define VM_GUEST_INFO_OS_NAME		6
#define VM_GUEST_INFO_UPTIME		7
#define VM_GUEST_INFO_MEMORY		8
#define VM_GUEST_INFO_IP_ADDRESS_V2	9

So we could workaround by detecting openbsd and accepting ipaddress, which is a little hacky?

**Comment by vancluever** [comment]
Hey @braddeicide,

The original philosophy behind waiting for a routeable address is that we need to make sure that one is reported to the provisioner, if at all possible - a non-routeable address is no good if you can't reach it.

I think the way forward here is to loosen this with a flag - something like `wait_for_guest_net_routeable` - which will be `true` by default. If `false`, it will skip the logic that checks to see if the IP address is routeable and just pass on any discovered IPv4 (probably excluding auto-configuration).

I don't think OS detection is necessary here and could be a slippery slope - I'd rather that this be solved through explicit configuration.

I've marked this as an enhancement so that we can work on it accordingly.

Thanks!

**Comment by sofixa** [comment]
+1, We have a similar need (no defaut gateway at start, it's added later on with Chef, so currently terraform doesn't work (just timeouts) without wait_for_guest_net_timeout=0), it'd be pretty nice to have an option to skip that check.

**Comment by vancluever** [comment]
Hey all, #470 has now been merged which allows you to control the routable behaviour of the network waiter. Keep an eye out for 1.4.1 which will probably be out this week!
