### ISSUE TITLE
cloning templates

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#353]
currently the clone sub-resource requires a template_uuid.  

Currently we have a process that updates the template (a packer job), which is essentially a destroy and rebuild the vm template.  If I use lifecycle ignore changes, (since I'm in a module) I can't ever update the resource to say "latest"

Is it possible to provide a name, instead of a uuid to prevent TF from forcing new resource upon template updates?  

Ideally I only want to keep 2 templates (stable and latest), and not manage them at a uuid.  Once a vm is built in the real world, I'm not sure what the connection is to the template it was built upon...

Thanks, and if I am not clear, or you have questions, let me know.

**Comment by vancluever** [comment]
Hey @rismoney,

Unfortunately you can't supply a template name - this was the old behaviour and to be consistent with our continued efforts to make sure that all resources in the provider take unique inputs (versus the old state where it took the more ambiguous names and paths), this was changed to be a UUID, and won't be reverted.

What might help in understanding the situation (and possibly why a VM's name, being mutable, is not a good choice for an input to a unique template attribute), is to compare the `vsphere_virtual_machine` resource and counterpart data source to the [`aws_instance` resource](https://www.terraform.io/docs/providers/aws/r/instance.html) and the [`aws_ami` data source](https://www.terraform.io/docs/providers/aws/d/ami.html). As you might be familiar with, an AWS instance is created off an image - an AMI, which cannot be changed without destroying that instance and re-creating it. We reflect that in the `aws_instance` resource by having the `ami` attribute force a new resource if changed. This is analogous to the `template_uuid` attribute in the `vsphere_virtual_machine` resource.

Both an AWS AMI ID and the UUID of a source virtual machine in vSphere are unique attributes and cannot be changed. Since the name of a VM is a mutable attribute, it could be more viewed as a kind of a tag of sorts (and indeed, there is some sugar in some parts of the AWS console that will take a tag named "Name" and display it as a friendly name for the resource in question).

This brings us to the parallels that can be drawn with the `vsphere_virtual_machine` and `aws_ami` data sources. You can view these more as image searches versus actually providing data on a literal unique image. The only difference is really in the terminology and the search terms that are being used, and nothing is really stopping this process from returning different templates/images for the same search criteria if things have changed appropriately outside of Terraform, through something like Packer.

(Just as a little bit of a tangent, forcing new resources upon template update might be intended behaviour - especially for more purpose-built images like web applications and what not where everything is baked in, you might be relying on tagging/naming behaviour to always return a latest image and force a re-creation of resources as part of your update cycle.)

With all that context, the question really is how you get unique, unchanging data into both? The answer to this is to supply the IDs in a way that you know will not change from run to run. Packer will, for example, report the AMI ID of a created AWS image after the appropriate builder is run. I don't know if that's the case for virtual machines though, so what might need to be done instead is to have part of your build process grab the UUID (via something like PowerCLI or govc), and supply that as a variable to each Terraform configuration instead. This will make sure that the value never changes. You then would just drop the `vsphere_virtual_machine` data source, and ensure that the UUID used never changes in that particular Terraform configuration.

Also, to answer your other question, what the relation between a VM and the VM that it's cloned off of is: for regular clones, not much. It's a unique copy. Linked clones, however, are cloned off of a snapshot, so if the parent VM goes away, it could potentially have disastrous consequences for the child virtual machine. To confuse matters a bit though, some vMotion scenarios will actually de-couple the clone from the snapshot (usually related to storage vMotion to a datastore where the child disks can't be properly linked back to the parent).

Hopefully this reply wasn't too much - I think it's important though to explain the context behind our decision to use UUIDs instead of names, and the precedent that exists in other parts of the Terraform space, and in the cloud in general!

**Comment by rismoney** [comment]
So to confirm IIUC, the issue is that I am dynamically discovering the template UUID via
```
data "vsphere_virtual_machine" "template" {
  name          = "${var.template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
```

If I instead supply the clone `template_uuid` parameter through say via an external variable I can ensure this is a static value.  I'm hoping if I delete the underlying template, it leaves existing topology in place.  The data source is what is performing the uuid lookup against a name, not the resource.  If the resource uuid matches the statefile, it should noop.

**Comment by vancluever** [comment]
@rismoney exactly. If the UUID doesn't change, then TF won't force a new resource as part of the plan, so if you supply it without the data source, you'll be good!

**Comment by sofixa** [comment]
@vancluever, and what happens if the UUID no longer exists? Won't terraform block on refreshing and want to destroy the ressource?

**Comment by rismoney** [comment]
This will work!  Thank you for all your help.

One final question- 
If I only have the uuid, can I infer the network_interface_types exported by that resource?  Not sure how to get the template name with just knowing the uuid.   Currently the data source vsphere_virtual_machine requires a name to be passed in.

I would think we would want to be able to go from both uuid->name and name-> uuid.

**Comment by jeremycornett** [comment]
@rismoney I tried to put a static value for the UUID which matched the current UUID of the template.

> variable "vm_clone_from" { default = "templates/template-pta-centos-7.3" }
> variable "uuid_vm_clone" { default = "421bd1c6-4906-ffe2-5141-580622d5963d" }

> data "vsphere_virtual_machine" "template" {
>     name          = "${var.vm_clone_from}"
>     datacenter_id = "${data.vsphere_datacenter.dc.id}"
> }
>
> resource "vsphere_virtual_machine" "vm" {
> ...
> clone {
> template_uuid = "${var.uuid_vm_clone}"

I then reran my Packer script which recreated the template VM, and then I reran my terraform plan. The plan failed. Am I misunderstanding the proposed solution here?

> module.SLCJenkinsNodeDocker01.vsphere_virtual_machine.vm: cannot locate virtual machine or template with UUID "421bd1c6-4906-ffe2-5141-580622d5963d": virtual machine with UUID "421bd1c6-4906-ffe2-5141-580622d5963d" not found

**Comment by bpoland** [comment]
Proposed solution is to remove the vsphere_virtual_machine data source, and only provide the UUID when cloning (which you would have to grab beforehand with govc or another method).  But as @rismoney said above, it's not clear how to grab details about that template VM if you only have the UUID (for example network interface types which is also needed for cloning).

**Comment by hmalinov** [comment]
@rismoney You may try using ignore changes like:

```
  lifecycle {
    ignore_changes = ["disk.0.disk_sharing", "disk.1.disk_sharing", "disk.2.disk_sharing", "clone.0.template_uuid", "disk.0", "disk.#", "clone.0", "clone.#"]
  }
```

This way even if you change the template it will not apply the changes. However I am not sure if this is the best way.
