### ISSUE TITLE
Can "Latency Sensitivity" be configured for newly created VMs?

### ISSUE THREAD

**Issue by JamesTGrant** [terraform-providers/terraform-provider-vsphere#387]
Terraform version 0.11.3
terraform-provider-vsphere_v1.3.1_x4.exe

Some of the VMs I manage require Latency Sensitivity="high"

Is it possible to control this setting when creating VMs using Terraform with the vsphere provider plugin? If so, how can I do this?
If not, please could it be added?

vCenter web UI, VM edit settings -> VM Options -> Advanced -> Latency Sensitivity

vCenter API 
Data Object Type: LatencySensitivity
Property Path: config.latencySensitivity
Properties:
    Name: level
    Type: LatencySensitivitySensitivityLevel
    Value: "high"
(other allowed values: "low" "normal" "medium")

vCenter web UI setting shown in the pic attached below:
![image](https://user-images.githubusercontent.com/32845298/35861229-d0208024-0b3e-11e8-8c22-2d5008932c63.png)

**Comment by vancluever** [comment]
Hey @JamesTGrant, there is no way to do this in the vSphere provider currently so it would have to be exposed. You might be able to change it using `govc` in a provisioner, but YMMV:

```hcl
provisioner "local-exec" {
  command = "govc vm.change -vm.uuid=${self.id} -e sched.cpu.latencySensitivity=high"
}
```

(Note that you would need to have your env set up for govc if you do do this - see [here](https://github.com/vmware/govmomi/tree/master/govc#usage))

I've tagged this as an enhancement so that we might be able to possibly look into exposing this setting.

Thanks!

**Comment by JamesTGrant** [comment]
Most excellent, thank you.
I’m running Terraform on Windows, but I’ll take the idea and run with it!

Kind regards,

James Grant
Mobile +44 (0) 7881 91 4053
james.j.grant@ericsson.com

**Comment by vancluever** [comment]
Hey @JamesTGrant, I don't know why I didn't tell you before as well, but you could possibly put this in `extra_config` map as well:

```hcl
resource "vsphere_virtual_machine" "vm" {
...

  extra_config {
    "sched.cpu.latencySensitivity" = "high"
  }
}
```

Again, this may or may not work, as usually values that are editable otherwise in the GUI or API are not necessarily editable in `extra_config`, however people have had success updating certain values this way before.

**Comment by JamesTGrant** [comment]
```
resource "vsphere_virtual_machine" "vm" {
...

  extra_config {
    "sched.cpu.latencySensitivity" = "high"
  }
}
```

Works perfectly. Just remember to set `memory_reservation` in addition to` memory`
Not only is it perfect - it also makes the changes 'in-place' so no need to destroy and recreate.
Thank you Chris - this is really perfect.

**Comment by vancluever** [comment]
Hey @JamesTGrant, that's great! Glad it worked out :+1:

Will leave this open until we expose this option in actual config.

**Comment by figo** [comment]
@JamesTGrant  with the fix, you should able to create high latencySensitivity VM by
either:
    `
      latency_sensitivity = "high" 
      memory_reservation = $memory
    `
or:    
   `
    extra_config  {
       "sched.cpu.latencySensitivity" = "high"
    } 
    memory_reservation = $memory
    `

Thanks
