### ISSUE TITLE
Question- regarding disk subresource on virtual machine

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#401]
Is there a way to have this resource present in a config, but not have it create under certain circumstances.
Obviously there is no count on disks, but I want to essentially do something like

```
resource "vsphere_virtual_machine" "foo" {
...
  disk {
   ...
   count = "${var.something ? 1 : 0}"
  }
}
```

**Comment by vancluever** [comment]
Hey @rismoney, not currently, but this is more specifically a larger HCL issue and may be fixed in future versions of Terraform. Right now it's hard to make conditionals for complex sub-resources (read: impossible) in this form, due to the the fact of what you specified in terms of sub-resources lacking the ability to leverage `count`.

[Here is a post](https://github.com/hashicorp/terraform/issues/7034#issuecomment-359311997) from @apparentlymart discussing this issue in TF core. Keep in mind that all of this work is currently in draft and may not reflect exactly what ultimately gets implemented.

Thanks!
