### ISSUE TITLE
virtual machine additional resources idea [enhancement]

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#415]
Network and disk as a subresource of the virtual machine (aka inline block), makes it particularly difficult to create machines with unique disk and network configurations when they are part of modules.  It essentially requires a unique module per machine type and limits flexibility of modules for future expansion.

Is it possible to have a virtual_machine_netadapter and virtual_machine_disk resource, that each have a vsphere_virtual_machine_id parameter.   This would be the inverse of attach.

A similar scenario is here:
https://www.terraform.io/docs/providers/aws/r/route.html

Not sure if the effort behind something like this is syntactical sugar, or a major overhaul.

**Comment by vancluever** [comment]
Hey @rismoney, this is definitely a legitimate consideration. Part of the reason surrounding the way the sub-resources are organized right now is to try and be able to facilitate these kinds of resources in the future.

The challenge, as it is with any Terraform provider (including the respective AWS resources), is in making a best effort to ensure that both inline and externally attached resources can either co-exist completely, or exist in a way that allows baseline functionality so that the resource (a virtual machine in this case) can pass creation. This is tricky because in Terraform we always need to reconcile the state of a particular resource with the actual configuration, and a resource (rightfully) only knows about what it's specifically configured for. So you run into scenarios that we have to warn for as mentioned in various parts of the AWS documentation, such as [here](https://www.terraform.io/docs/providers/aws/r/volume_attachment.html).

The extra challenge for us in vSphere land is that there is no API between us and the lower level management interface of the virtual hardware - there's no such thing as an ENIs in vSphere (which also includes layer 4 if you take EIPs into consideration), and EBS kind of needs to be "emulated" via the creation of external virtual disks (via things like `vsphere_virtual_disk`) and then attached to a virtual machine as an external disk, with Terraform actually handling the safe detachment upon removal of the resource. Further to that, there's no concept of a "root disk" as exists in many cloud services today, so the VM resource has no choice but to manage _all_ disks.

In any case, my ideas so far on the matter have been possibly to have a setting that restricts the disks we scan on the SCSI bus, or possibly a new `system_disk` sub-resource that can only be declared as a single instance of the current `disk` sub-resource, for which the presence of and the lack of any `disk` sub-resources would mean that the resource would not attempt to check the state of any disk past unit number 0, and hence not attempt to detach any disks it saw as "orphaned" in the configuration.

This is not necessarily on the roadmap right now, but definitely is something we are aware of!

**Comment by surajsub** [comment]
Any update on this . This would be a good feature that will really help in the wider adoption of tf across the community . Appreciate any insight and response to know  if this is being planned in the near future of the provider.

**Comment by uberjew666** [comment]
Although Terraform 0.12 isn't out yet, I was reading through some of the new features.
I wonder if Dynamic Nested Blocks may resolve this issue?
https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each
This would allow both multiple disk and multiple network interface, all dependant on list or list of maps.

I did brief mock up using their proposed syntax:
`
variable "disk" {
  default = [
    {
      label   = "first-disk"
      number = 1
      size = 30
      provisioned = false
    },
    {
      label   = "second-disk"
      number = 2
      size = 60
      provisioned = true
    },
    {
      name   = "third-disk"
      number = 3
      size = 20
      provisioned = true
    },
  ]
}

dynamic "disk" {
  for_each = [for s in disks: {
    label = s.label
  }]

  content {
    label = disk.label
    size = disk.size
    unit_number = disk.number
    thin_provisioned = disk.provisioned
  }
}`

**Comment by tigerhawk6** [comment]
Has anyone had a chance to test this yet?  I've seen it posted as a potential option in a couple places but never heard if it works.  I'm needing to do the same thing for a project I'm on.

**Comment by AranVinkItility** [comment]
Second this feature request. I'm using Terraform 1.11 and cannot switch to 1.12 anytime soon.

I wrote a workaround using a conditional count for different disk counts and defined the disks within. My luck is that I only have to support 3 different disk counts in my module, so code duplication is limited, but still not ideal. Other downside is that when changing disk count the provider will always recreate the resource, since it is defined in a different resource block.

Just posting a snippet of my hack here in case anyone would like to use it:
```
resource "vsphere_virtual_machine" "vsphere-vm" {
  #Only create when 4 disks are needed
  count = "${lookup(var.data_disks_count_by_type, var.vm-type) == 4 ? 1 : 0}"
  disk { #disk1 }
  disk { #disk2 }
  disk { #disk3 }
  disk { #disk4 }
}

resource "vsphere_virtual_machine" "vsphere-vm" {
  #Only create when 1 disk is needed
  count = "${lookup(var.data_disks_count_by_type, var.vm-type) == 1 ? 1 : 0}"
  disk { #disk1 }
}
#etc...
```

**Comment by rismoney** [comment]
my workaround to date, is create 3 different modules each identical with a different set of disks within, and when i want to increase the disks i just change which module I target. 

```terraform
source = "git::ssh://git@example.com/inf/tf-mod.git//ec2_ubuntu_1disk?ref=1.0"
source = "git::ssh://git@example.com/inf/tf-mod.git//ec2_ubuntu_2disk?ref=1.0"
source = "git::ssh://git@example.com/inf/tf-mod.git//ec2_ubuntu_3disk?ref=1.0"
```

highly annoying duplicative code to maintain ,but i see no other clean way that avoids rebuilds.
like you I am going to avoid .12... like the plague. 

on a side note,  I think the core dev team for TF have lost their minds managing release cycles, and criteria for releasing.   What happened to faster cadences of small changes?  Seems like crashing waterfall, and the issue tracker is hopeless polluted.

**Comment by rismoney** [comment]
The code @uberjew666 above doesn't work, and I get `There is no variable named "disks".`

Essentially what I have been trying to workup but doesn't would like to do is have:
```module {
 source = "../myvsphere"
 ...
  drives = ["100","20"]
...
}
```

In the module:
Something like this (which i haven't been able to get working.

```
    dynamic "disk" {
    for_each = [for s in disk_sizes: {
      label = s.index == 0 ? "${var.name}.vmdk" : "${var.name}_{s.index}.vmdk"
    }]

    content {
      label = disk.label
      size = disk.size
      unit_number = disk.index
      thin_provisioned = true
    }
  }
 ```

**Comment by rismoney** [comment]
Alright I got this working: (I deleted a msg I wrote an hour ago)
Here is what I did:

**Comment by rismoney** [comment]
```hcl
variable "disks" {
  default = [
    {
      unit_number = 0
      size = "80"
      thin_provisioned = true
    },
  ]
}

  dynamic "disk" {
    for_each = [for s in var.disks: {
      label = s.unit_number == "0" ? "${var.name}.vmdk" : "${var.name}_${s.unit_number}.vmdk"
      unit_number = s.unit_number
      size = s.size
      thin_provisioned = contains(keys(s),"thin_provisioned") ? s.thin_provisioned : "true"
    }]
    content {
      label = disk.value.label
      unit_number = disk.value.unit_number
      size = disk.value.size
      thin_provisioned = disk.value.thin_provisioned
    }
  }
```

Then when I call my module:
module "ifel-nj-dev01" {
  source = "../modules/vsphere67"
  providers = {
    vsphere = "vsphere.vspherepsnj"
  }
  name   = "myhost"
  ...
  total_vcpu   = "4"...
  disks = [{
    unit_number = "0"
    size = "100"
  },{
    unit_number = "1"
    size = "100"
  }]
}

**Comment by rismoney** [comment]
Any thoughts on how to do looping for network interfaces?  
Not sure how to incorporate `data "vsphere_network" "network"`

**Comment by rismoney** [comment]
https://discuss.hashicorp.com/t/dynamic-blocks-involving-data-sources/1695/4

@vancluever - i think this issue can be closed - thoughts?

**Comment by bill-rich** [comment]
Thanks @rismoney! I believe that covers it. I'll get this issue closed.
