### ISSUE TITLE
VM with a bootable CD cloned from a template don't boot from hard disk but from CD

### ISSUE THREAD

**Issue by GMZwinge** [terraform-providers/terraform-provider-vsphere#420]
The root cause is that the .vmx file created by the providers contains bios.bootOrder = "cdrom". To boot from hard disk, it would need to contain bios.bootorder = "hdd", or it could get it's value from the template. Eg: Packer sets the value to bios.bootorder = "hdd,CDROM".

Boot options at https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#boot-options could have an option for boot_order that could be set to 'hdd', 'cdrom' or even 'hdd,cdrom'. That option could set the value of bios.bootOrder in the .vmx file.

From looking at the code, it seems that it could be handled just like boot_delay.

### Terraform Version

bin\terraform.exe -v
Terraform v0.11.3
+ provider.vsphere v1.3.3

### vSphere Provider Version

bin\terraform.exe providers
.
└── provider.vsphere

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  cdrom {
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    path         = "packer_cache/CentOS-7-x86_64-DVD-1708.iso"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }
}
```

Based on https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#cloning-and-customization-example.

### Expected Behavior

VM cloned from a template by Terraform with a CD should be able to boot from the hard disk even if the CD contains a bootable images (eg: OS iso).

### Actual Behavior

The VM boots from the CD, because the .vmx file contains:

bios.bootOrder = "cdrom"

When it could contain:

bios.bootOrder = "hdd"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

BootOrder is already available in https://raw.githubusercontent.com/terraform-providers/terraform-provider-vsphere/master/vendor/github.com/vmware/govmomi/vim25/types/types.go.

### References

boot_delay at https://github.com/terraform-providers/terraform-provider-vsphere/blob/79e7cf2ea347f57d41043d8cf0bf3c292bbe6c95/vsphere/virtual_machine_config_structure.go#L73.

**Comment by vancluever** [comment]
Hey @GMZwinge, modifying the boot order is actually a complex operation that requires access to device keys in the vSphere API. Our device management and general configuration management workflows are handled separate to each other and hence the latter workflow does not have easy access to the former.

It should be noted that VMware does not even allow modification of this in the vSphere client, rather requiring that you do it in the in-VM BIOS configuration (unless you did it through advanced configuration).

Unfortunately as a result of this I don't see us supporting this any time soon. The best thing I can recommend is to adjust your workflow so that you don't have to depend on booting off of a CDROM, which may ultimately require some odd workflows to fully automate regardless of if we supported adjusting the boot order.

Thanks and sorry for the delays!

PS: You _may_ also be able to have some luck in modifying your source VM template's settings, as if you do that, those settings may persist, as we don't modify the boot order when cloning. This is not guaranteed to work though.

**Comment by GMZwinge** [comment]
@vancluever I figured out the root cause of the boot order being reset to "cdrom": the hdd order must also be set in the .vmtx file, for example bios.hddOrder = "scsi0:0".

So the workaround for this issue is to set both boot order and hdd order in the template. Packer only sets boot order. I can use vmx_data_post in the Packer template to add the hdd order. If I have time, I'll open a ticket with Packer to either address the missing hdd order, or document the need.

**Comment by vancluever** [comment]
@GMZwinge glad you figured out a solution! From a authoring perspective Packer would definitely be the place to open an issue like this as it has a lot of powerful tools at its disposal to do this stuff (as you've seen). At the very least maybe a bit of documentation could be added to the VMware builders to note the configuration required to get the correct boot order in the template.

Thanks!
