### ISSUE TITLE
Count on network_interface subresource

### ISSUE THREAD

**Issue by sofixa** [terraform-providers/terraform-provider-vsphere#473]
Hi,

### Terraform Version

0.11

### vSphere Provider Version

1.3.3

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
  network_interface {
    count = 3
    network_id = "${data.vsphere_network.si.id}"
    adapter_type = "${var.network_interface_type}"
  }
```
### Expected Behavior

Ideally count should work so that we can use a list variable to populate as much network_interface subresources as needed while in a module.

### Actual Behavior

```
Error: vsphere_virtual_machine.vm-01: network_interface.1: invalid or unknown key: count
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Create a virtual machine resource with a network interface using count
2. terraform apply

Is that a feature that might be supported? If not, is there some sort of workaround possible?

Cheers,
Adrian

**Comment by vancluever** [comment]
Hey @sofixa, unfortunately `count` on sub-resources is not possible. This is a long-standing Terraform core issue and will not be fixed any time soon. Sorry!

**Comment by sofixa** [comment]
@vancluever i was just discussing this with a colleague, and he pointed out that having a dedicated, but optional resource for network interfaces would solve this issue - something like the [AWS provider SG resource](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html).

Our use case is a module to abstract the big amount of parameters the virtual machine resource needs that our "users" don't need nor care for, and having flexibility in implementing that would be pretty cool.

**Comment by vancluever** [comment]
@sofixa we are currently not planning on looking into any more additional `*_attachment` resources at this point in time, mainly because there is not much of a facility in vSphere to support these kinds of things. Unlike a cloud provider like AWS, vSphere does not provide an API for management of external block devices and NICs in a stateful fashion. In order to get this right in `vsphere_virtual_machine`, we have had to write a very complex lifecycle management backend that, while was written with the possibility of supporting external attachments in the future, the current implementation is fairly coupled to the resource.

Going further on this topic, resources like [aws_security_group_rule](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html) usually rely on an all-or-nothing approach to their dependencies - applying this to NICs or disks, that would mean that the base VM would have to have either separate resources for base disks and NICs or none at all when they were created. The first creates a bit of a disjointed UX and the second one will be pretty much impossible (although we are contemplating supporting diskless VMs in the future, a lack of either one of these devices in an initial VM configuration would in most scenarios create a inoperable VM).

One thing that I can share about changes coming to TF is the `dynamic` HCL extension that will be coming in a future TF release. This will generate configuration blocks that will effectively allow for repeatable, parameterized sub-resources. For more details, you can start reading hashicorp/terraform#7034 starting from about [here](https://github.com/hashicorp/terraform/issues/7034#issuecomment-359311997). Based on the context given there, it should address the use case you are concerned with.

Thanks!
