### ISSUE TITLE
allow placement on datastore or datastore cluster

### ISSUE THREAD

**Issue by bleything** [terraform-providers/terraform-provider-vsphere#483]
Feature request! 

I manage a cluster that has both vSAN and a traditional SAN. I'm trying to get everything under terraform management and the one place I'm stuck is writing a module that can place a VM on either vSAN or an SDRS cluster depending on its inputs. I could create two modules but I'd be duplicating a looooot of config and I'd really rather not.

What I'd like to be able to do in my module is this:

```hcl
resource "vsphere_virtual_machine" "vm" {
    # ...
    datastore_id = "${var.datastore_id}"
    datastore_cluster_id = "${var.datastore_cluster_id}"
    # ...
}
```

The way I'd use that is both of those variables would have a default value of the empty string and I'd pass whichever one I wanted in via the module's inputs:

```hcl
module "vm_vsan" {
    source = "modules/vm"
    datastore_id = "${data.vsphere_datastore.vsan.id}"
}

module "vm_iscsi" {
    source = "modules/vm"
    datastore_cluster_id = "${data.vsphere_datastore_cluster.iscsi_san.id}"
}
```

I tried to do this with the current provider but it won't allow me to declare both of those arguments simultaneously, even if the value of one is empty.

I can work around this by creating an SDRS cluster that only contains the vSAN datastore, but that's a hack and I'd rather be able to do this properly.

### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.vsphere v1.4.0
```

### Affected Resource(s)

- `vsphere_virtual_machine`

**Comment by vancluever** [comment]
Hey @bleything, this is definitely a valid use case and I personally have advocated for exploiting zero values in the past, but in this instance the reason why this does not 100% work as expected is that we have logic that performs certain tasks depending on whether or not one value or the other exists during the planning phase, even if we don't know the final value (example: when you are creating a datastore or datastore cluster in the same config and it has not been created yet). In these cases, the value of `datastore_id` or `datastore_cluster_id` will come up as empty strings, so it's important that we differentiate between empty or "unknown". The problem you are hitting is that even in defining a zero value, it is still "known", but as an invalid zero value.

While not possible to specify "unspecified" values currently, future versions of Terraform are making several changes to HCL that should make this possible to do so, allowing the ability to have a module that can specify either a real or null value depending on a conditional, allowing the use of a single module without having to make modifications to this model. The final implementation is not set in stone, and we might not know for sure if this will fix things 100% until the the final implementation is released. I'm going to keep this open for now so that we can re-visit it when this does happen, to see if any changes to the implementation need to happen to support this use case or if it will be feasible.

Sorry for the inconvenience in the meantime!

**Comment by vancluever** [comment]
Just wanted to note that @tthayer's approach is exactly how I've handed things like this in the past - not necessarily related to vSphere for for other TF resources that have similar issues. It's not 100% optimal, but it helps abstract it away.

**Comment by bcornils** [comment]
This should be addressed in our 0.12 release.

**Comment by bill-rich** [comment]
Hi @bleything! Now that Terraform v0.12 has been released, you should be able to include both `datastore_id` and `datastore_cluster_id` as long as one of the values is `null`. When defining the variables, just set their default to null, and then specify a value for the one you would like to use.

**Comment by Koleon** [comment]
Hey @bill-rich I tried your advice how to set up `resource "vsphere_virtual_machine"` with `datastore_id` and `datastore_cluster_id`. 

Unfortunately when I run the module with `datastore_id` or `datastore_cluster_id` specified, I get error `Error: "name": required field is not set`. Even though both variables are set with `default = null`. 
As long as I set both values then I get `Error: "datastore_id": conflicts with datastore_cluster_id` and `Error: "datastore_cluster_id": conflicts with datastore_id` as I would expect. 

Could you help me with this please?

**Comment by pratikpotdar** [comment]
As @Koleon mentioned in the last comment, I'm getting the same error. Is there some thing which we are doing wrong?

**Comment by Koleon** [comment]
@pratikpotdar hey, I haven't found suitable solution yet. :disappointed:
