### ISSUE TITLE
CDROM device is required even when not specifying vApp properties

### ISSUE THREAD

**Issue by bpoland** [terraform-providers/terraform-provider-vsphere#489]
### Terraform Version
Terraform v0.11.7

### vSphere Provider Version
1.4.1

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files
Pretty standard vsphere_virtual_machine with no cdrom device in the template or in config, and no vapp section

### Debug Output
Error: Error running plan: 1 error(s) occurred:
* vsphere_virtual_machine.sad: 1 error(s) occurred:
* vsphere_virtual_machine.sad: this virtual machine requires a client CDROM device to deliver vApp properties

### Panic Output
N/A

### Expected Behavior
Terraform should have created the VM

### Actual Behavior
Terraform required the VM to have a cdrom

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This was working with provider 1.3.1 and the same terraform config.  I believe this change by @bill-rich introduced the issue: https://github.com/terraform-providers/terraform-provider-vsphere/pull/440

It seems like in https://github.com/terraform-providers/terraform-provider-vsphere/pull/440/files#diff-9e9cbc609d70c3e542915a469081b985 line 568, the call to VerifyVAppTransport should only run when the VM has a vapp section.

### References
- https://github.com/terraform-providers/terraform-provider-vsphere/pull/440

**Comment by vancluever** [comment]
@bpoland thanks for submitting the issue. Can you confirm for me whether or not your source template actually has vApp properties being delivered over an ISO transport? If the template came from an OVF/OVA, then this is definitely a possibility.

This should only be triggering in those situations, and I don't think we will be rolling this back so that it functions as expected here, as there are several vApp/OVF-related things that we are still looking at adding that will make a OVF configuration _without_ vApp properties to be entirely plausible, such as #394, which is an open request for the resource to support templates with non-configurable properties. This could reasonably mean that there could be a situation where a OVF template may have no configurable properties, at which point it omitting `vapp` entirely would be reasonable.

To get around this, you can add a client-device CDROM to your configuration:

```hcl
resource "vsphere_virtual_machine" "foo" {
  ...

  cdrom {
    client_device = true
  }
}
```

Thanks!

**Comment by bill-rich** [comment]
Hi @bpoland! You can check if the VM has vApp options enabled through the flash web client. First you'll need to convert the source template to a VM, edit the settings, and go to "vApp Options". From there you can see if vApp options are enabled, which properties are available, and which OVF environment transports are enabled. If the "ISO Image" environment transport is enabled, a client CDROM device will be required in the virtual machine configuration.

**Comment by bpoland** [comment]
Thanks, yes the vApp options were enabled on my template.  I just turned them off because we don't use them, and was able to clone using the new provider.  Thanks for the help @vancluever and @bill-rich !
