### ISSUE TITLE
Terraform crash while creating VM's

### ISSUE THREAD

**Issue by Nishmita** [terraform-providers/terraform-provider-vsphere#494]
Hi there,

### Terraform Version and  vSphere Provider Version

nish@ubuntu:~/go/bin$ ./terraform version
Terraform v0.11.7
+ provider.nsxt v1.0.0
+ provider.vsphere v1.3.3

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```
# =====================create VM's =================================== 

resource "vsphere_virtual_machine" "vm1" {
  count = "${var.t_vm["count"]}"
  name = "${format("vm_%03d", count.index + 1)}"
  
  #output "vmprefix" {
  #  value = "${var.t_vm["vm_name"]}"
  #}
  #name  = "${format("vmprefix-%03d", count.index + 1)}"
  #ip   = "${format("192.168.1.%d", count.index + 2)}"

  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus = 6
  memory   = 8192
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
  # Attach the VM to the network data source that refers to the newly created logical switch
  network_interface {
    network_id = "${data.vsphere_network.terraform_testvm.id}"
  }
  disk {
    label            = "${var.t_vm["vm_name"]}.vmdk"
    size             = "100"
    thin_provisioned = true
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    customize {
      linux_options {
        host_name = "${var.t_vm["vm_name"]}"
        #host_name = "${format(${var.t_vm["vm_name"]}-count.index + 2)}"
        domain    = "${var.t_vm["domain"]}"
      }
      network_interface {
        ipv4_address = "${format("192.168.1.%d", count.index + 2)}"
        ipv4_netmask = "${var.t_vm["mask"]}"
      }

      ipv4_gateway = "${var.t_vm["gw"]}"
    }
  }
}
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output:
https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the
debug output in the issue; just paste a link to the Gist.

### Panic Output

https://gist.github.com/Nishmita/d0c40dd9e6d21be3c2e8822be06e6faa

### Expected Behavior

Expected to create 2 VM's

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Steps to Reproduce

`terraform plan`

**Comment by vancluever** [comment]
Hey @Nishmita, this is a tough one namely because it looks like a provider SDK issue. You can see hashicorp/terraform#9488 for some of the background, but long story short there seems like some possible issue in interpolation and validation that ultimately is allowing bad data to enter configuration in a way that is unresolvable at plan time.

We can't necessarily do much about it in the provider here. What I can recommend though is that you review most of the computed inputs to the resource and see if you can find the variable that's the culprit, and then correct it so you don't get the panic. If you don't mind, if you can let me know what field it was that would be great.

Thanks!

**Comment by Nishmita** [comment]
Hi Vancluever,

Thanks for you input.
I was able to identify what was the problem by trial & error method.
In the Panic error message i could see below error, from which type mismatch error is understandable, but which variable/where was not clear , can we improvise on the error message displayed?

Error: Error refreshing state: 1 error(s) occurred:
* data.vsphere_network.terraform_testvm: 1 error(s) occurred:
* data.vsphere_network.terraform_testvm: unexpected EOF

panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'


Issue was :
name = "${nsxt_logical_switch.LS1.*.display_name}"

changed it to 
name = "${nsxt_logical_switch.LS1.display_name}"

Then it worked 

Regards,
Nishmitha

**Comment by vancluever** [comment]
Thanks @Nishmita! Glad you were able to figure it out.

Actually, the issue is with the resource address. You had `nsxt_logical_switch.LS1.*.display_name` when a `count` has more than likely not been specified. This would give you an error as supplied above.

As mentioned this is not something that is properly validated during the plan phase right now, but unfortunately is out of the scope of what we can do within the provider to fix. With that said, I'd watch the issue that I mentioned for updates on when the issue may be fixed.

Thanks!
