### ISSUE TITLE
windows_sysprep_text times out waiting for customization

### ISSUE THREAD

**Issue by k-brooks** [terraform-providers/terraform-provider-vsphere#517]
### Terraform Version
0.11.7

### vSphere Provider Version
1.4.1

### Affected Resource(s)

`vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  password = "pw"
  user = "user"
  vsphere_server = "vsphere"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "dc"
}

data "vsphere_datastore" "eng_ds" {
  name = "eng"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name = "pool"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name = "Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "test-clone" {
  datastore_id = "${data.vsphere_datastore.eng_ds.id}"
  name = "TestCloneKB5"
  num_cpus = 4
  memory = 8192

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
    adapter_type = "e1000"
  }
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  guest_id = "windows9Server64Guest"

  clone {
    template_uuid = "4200edb6-9aac-a75a-aa31-a8e1a1cec042"
    linked_clone = true
    customize {
      windows_sysprep_text = "${file("unattended.xml")}"
      network_interface {
        ipv4_netmask = 22
      }
    }
  }
  scsi_type = "lsilogic-sas"
  disk {
    unit_number = 0
    datastore_id = "${data.vsphere_datastore.eng_ds.id}"
    label = "disk0"
    size = 60
    thin_provisioned = true
  }

  provisioner "file" {
    source = "variables.tf"
    destination = "C:/temp/variables.tf"

    connection {
      insecure = true
      host = "TestCloneKB5"
      type = "winrm"
      user = "TestCloneKB5\\Administrator"
      password = "pw"
    }
  }
}

```

### Debug Output
https://gist.github.com/k-brooks/858eac42ff8de61da3f670a510c911f8

### Expected Behavior
- Terraform continues after customization completes

### Actual Behavior
- Terraform hangs, never detects completion of customization

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
- Vsphere version 6
- Template VM OS = Win Server 2016

**Comment by k-brooks** [comment]
Customization completes in 3-4 minutes.
System is online and reachable.
![image](https://user-images.githubusercontent.com/20670569/39842613-17561404-53b5-11e8-87c2-01a5bf2f4539.png)

**Comment by bill-rich** [comment]
It is likely that something is going wrong in the guest customization. The first thing to check is that your source VM meets the [requirements](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html) for guest OS customization on vSphere. The next would be to run through some cusomization [troubleshooting](https://kb.vmware.com/s/article/1026317). If everything looks ok on both of those, you can also try [manually setting up customization](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html) through the vCenter client.

Let me know if all of those steps check out and the issue is persisting.

**Comment by bill-rich** [comment]
It took me a while to get a response on this issue, so I've probably missed the window for being useful. If anyone is still experiencing this issue, please take a look at the troubleshooting steps listed above. If that doesn't point to a solution, please either let me know here and I'll reopen the issue, or open a new issue with the additional detail.
