### ISSUE TITLE
[enhancement] Exclude specific extra_config options from requiring VM restart

### ISSUE THREAD

**Issue by skywalk7** [terraform-providers/terraform-provider-vsphere#518]
Currently any changed extra_config option would require VM restart. I understand it can be a configuration safe default behavior, but for "guestinfo.*" options it is definitely not required.
I think it can be solved in 2 ways:
1. Ad-hoc fix to allow change "guestinfo.*" options without reboot
2. Allow to explicitly define list of options that do not require reboot to apply correctly.
Thanks in advance!

**Comment by vancluever** [comment]
@skywalk7, sorry, but this is not something that we plan on changing at this point in time. While modification of `extraConfig` is not an operation that requires a reboot in itself, in order for a good number of the options that can be set within it to take effect (including several in `guestinfo`, depending on the operating system that you are working under), a reboot is required. `extra_config` is set to trigger a restart as a result to ensure that the practitioner understands the weight of modifying this value in _most_ contexts across the board. If this is not a desirable behavior, the best recommendation I can give is to try and figure out a different way to apply the configuration options you need to apply, or otherwise plan your infrastructure in a way that can handle instance restarts.

Thanks!
