### ISSUE TITLE
cpu documentation clarification

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#532]
`num_cpus - (Optional) The number of virtual processors to assign to this virtual machine. Default: 1.`
`num_cores_per_socket - (Optional) The number of cores to distribute among the CPUs in this virtual machine. If specified, the value supplied to num_cpus must be evenly divisible by this value. Default: 1.
`

This is what the documentation states.

So there are two settings for a VM in vsphere - # of virtual sockets, and # of cores per socket.
It looks like the num_cores_per_socket is correct, but if both options are specified, num_cpus is using the total number of cores, instead of being the number of virtual sockets. 

Was trying to build a 1 socket 4 core box, and a 2 socket 2 core box, and I'm seeing some wierdness.

Specifically a 1 socket 4 core box, is showing up as 4 and 4 for both num_cores_per_socket and num_cpus respectively.

Am I misunderstanding?

**Comment by vancluever** [comment]
@rismoney I think the last assessment of 4/4 (4 CPUs, 4 cores per socket) should produce what you want.

Admittedly I do agree that our docs are a bit confusing, due to the confusion no the vSphere side on this one too and could use an example. Adding a note here.

Also, more info here: https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-A75B69D5-800A-41F5-8B80-8D410689184B.html

**Comment by rismoney** [comment]
yes, to clarify, the specification of the number of sockets the guests get, is not a configuration.  It is a calculation based on the total cpu's and the cores per socket.

**Comment by bill-rich** [comment]
#799 is open to clarify the relationship between vCPUs, sockets, and cores.
