### ISSUE TITLE
Force new resource on guest_id change

### ISSUE THREAD

**Issue by skywalk7** [terraform-providers/terraform-provider-vsphere#547]
Hi!
In our use case scenario we do not want to redeploy vm automatically when vm template was updated so we ignore changes on `clone.template_uuid`
At the same time if operating system was changed, we definitely want to recreate VMs. 
I was looking into `resource_vsphere_virtual_machine.go` and didn't find `guest_id` in the schema.
Is it possible to add it to schema and set `ForceNew` on it?
Thanks in advance!

**Comment by vancluever** [comment]
Hey @skywalk7, sorry, but I don't think that this is a good idea. OS type is not immutable in vSphere, hence it does not make sense for us to make it immutable in the resource. This also breaks the current interface in that nothing in the `vsphere_virtual_machine` resource actually forces a new resource except for changes to items in `clone`. This is by design.

The correct method would be to version your template naming in enough of a way that it can be paramterized and each Terraform project can be locked to a specific template. In the future, as well, we might release data sources that can assist with this in various ways (similar to features in [`aws_ami`](https://www.terraform.io/docs/providers/aws/d/ami.html), for example).

Thanks for understanding.
