### ISSUE TITLE
uuid.bios changed on some VMs after datacenter power failure and Terraform want create them again

### ISSUE THREAD

**Issue by olljanat** [terraform-providers/terraform-provider-vsphere#578]
### Terraform Version
Terraform v0.11.7

### vSphere Provider Version
v0.11.7.1

### Affected Resource(s)
- `vsphere_virtual_machine`

### Expected Behavior
If virtual machine is on existing location with existing name Terraform should detect them even when uuid.bios changes.

### Actual Behavior
Terraform refresh cleans all the references from state file  to existing servers which it cannot find with id and want create them again (which would fail as they still exists).

### Steps to Reproduce
Create VM using Terraform.
Power off whole vSphere, all the hosts and storage (datacenter power failure).
Start everything again.

### Important Factoids
vSphere 6.5 + Tintri VMstore T650

### Workaroud ###
Restore old state files from backup, download affected machines vmx files and update their uuid.bios values to state file manually.

**Comment by bill-rich** [comment]
Hey @olljanat! The BIOS UUID is used as the virtual machine ID because it should stay the same even across vCenter instances and it should not be changing unexpectedly. We have an [issue](https://github.com/terraform-providers/terraform-provider-vsphere/issues/282) open to switch to using the InstanceUUID instead of the BIOS UUID, but this would likely have changed in your situation also. 

Your workaround is probably the best way to handle this situation. Another option would be to delete the affected VMs from the state and import them again using the new UUIDs, though this could end up having other side effects based on the dependencies in your configuration.

If you'd like to avoid having the UUIDs change when the environment is powered down, you could check the vmx files to see if `uuid.action = "change"` is set (see [here](https://kb.vmware.com/s/article/1541) for more info), or check with your storage vendor to see if the UUID changes are expected.

**Comment by dannyk81** [comment]
Hi @bill-rich, I came across this issue after having a similar problem as reported by the OP, in our case the VMs in question have crashed due to a failed esxi server (hw failure) once HA has restored them on a different esxi they started up with a new UUID and any subsequent plan/apply wants to create the VM again.

This happens quite often as we have many different clusters and server failures are not uncommon.

Currently the only solution is to remove the VM from state (with the old UUID) and import it again with the new UUID, this works but is tedious and quite annoying.

I think the proper way to handle this would be to set `uuid.action` to `keep` which ensures that once a UUID is assigned it is never changed.

Although this has some caveats, for an environment managed by a tool like terraform this seems like a safe approach.

Wouldn't it be possible to set the `uuid.action` to `keep` for newly created VMs?
