### ISSUE TITLE
NSX for vsphere  Support

### ISSUE THREAD

**Issue by longname123** [terraform-providers/terraform-provider-vsphere#621]
Will there be support for NSX for vsphere in the future?

Thanks.

**Comment by surajsub** [comment]
There is already a nsx provider available .  Look here 

https://www.terraform.io/docs/providers/nsxt/index.html

**Comment by longname123** [comment]
Thanks for your reply, They support NSXT,  not NSX for vsphere

**Comment by bill-rich** [comment]
Sorry about that @longname123! We're probably going to be focusing more on NSX-T through that provider since that seems to be the direction VMware is going. Is there a specific set of features you are looking to get support for?

**Comment by longname123** [comment]
NSX supports SSL VPN

**Comment by bill-rich** [comment]
It looks like there are a couple community providers available for NSX, but I wasn't able to find any supporting the features you are looking for.

Since NSX uses a different API located on a different server, I believe it is outside of the scope of the vsphere provider. However, I'd recommend checking out one of the community providers and opening a feature request to see if the features you are looking for could be added.
