### ISSUE TITLE
Question: Can "vsphere_virtual_machine_snapshot" resource used to revert a VM to a particular snapshot ?

### ISSUE THREAD

**Issue by ananddaparthi** [terraform-providers/terraform-provider-vsphere#626]
I can create snapshots for my VMware VM's by using "**vsphere_virtual_machine_snapshot** resource". I was unable to find anything related to reverting a VM to a snapshot. Is there a way we can do that ? Thanks in advance.

**Comment by vancluever** [comment]
@ananddaparthi reverting to any snapshot that the vSphere provider creates needs to be done out-of-band.

Having revert logic within the provider (in the form of a resource or otherwise) was rejected during the PR process for `vsphere_virtual_machine_snapshot` on the grounds that it would not be manageable in any sort of stateful way. You can find the relevant conversation [here](https://github.com/terraform-providers/terraform-provider-vsphere/pull/107#issuecomment-327001399).

Thanks!
