### ISSUE TITLE
Using underscore in hostname

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#689]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

0.11

### vSphere Provider Version

1.8

Is there a reason why adding underscore in the hostname fails in vmware . This is supported via the UI but not via the tf provider? Any thoughts ?

**Comment by surajsub** [comment]
vmware version - 6.5

**Comment by bill-rich** [comment]
Hi @surajsub! I do not know of a limitation with underscores right off. Which resource or data source are you seeing the issue on? Please provide an example config and I'll try to reproduce the issue and dig into what it happening.

**Comment by surajsub** [comment]
This is related to vsphere resource specifically related to customization.
customize {
    
      timeout = "120"
      linux_options {
        host_name = "${var.name}" <-- If the name here has an "underscore" it fails
        domain    = "${var.dns_suffixes}"
      }

**Comment by bill-rich** [comment]
I looked into the [customization spec](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vm_admin.doc/GUID-9A5093A5-C54F-4502-941B-3F9C0F573A39.html) and it looks like only alphanumeric characters and hyphens are supported for `hostName`. Its odd that underscores are allowed through the UI, but it appears that rejecting underscores is the expected behavior for the API. Sorry for the confusion, but hope this helps!
