### ISSUE TITLE
Disk setting changes at some events: eagerly_scrub/thin_provisioned

### ISSUE THREAD

**Issue by thetuxkeeper** [terraform-providers/terraform-provider-vsphere#754]
### Terraform Version

Terraform v0.11.13
+ provider.vsphere v1.10.0

### vSphere Provider Version

1.10.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
  disk { 
    label = "coreos"
    thin_provisioned = true
    size = 16
  }
  
  disk { 
    label = "docker"
    thin_provisioned = true
    size = 16
    unit_number = 1
  }

```

### Debug Output

```
Error: Error running plan: 3 error(s) occurred:

* vsphere_virtual_machine.coreos-tst1-005: 1 error(s) occurred:

* vsphere_virtual_machine.coreos-tst1-005: disk.0: virtual disk "coreos": cannot change the value of "eagerly_scrub" - (old: true new: false)
* vsphere_virtual_machine.coreos-tst1-002: 1 error(s) occurred:

* vsphere_virtual_machine.coreos-tst1-002: disk.0: virtual disk "coreos": cannot change the value of "eagerly_scrub" - (old: true new: false)
* vsphere_virtual_machine.coreos-tst1-004: 1 error(s) occurred:

* vsphere_virtual_machine.coreos-tst1-004: disk.0: virtual disk "coreos": cannot change the value of "eagerly_scrub" - (old: true new: false)

```

### Expected Behavior

What should have happened?
Successful plan/apply

### Actual Behavior

What actually happened?
Terraform is failing to plan the changes.

### Steps to Reproduce

1. trigger change of disk type from thin provisioned to thick provisioned (use all the space of the disk in the VM?)
1. `terraform plan`

### Important Factoids

As replied in https://github.com/terraform-providers/terraform-provider-vsphere/issues/562#issuecomment-487277714
I think the problem is, that after creating the disk, vSphere changes the setting to a state type of information.
Likely when the disk gets used completely the thin_provisioned state changes to one of the thick provisioned states.
I have seen this multiple time with manually created VMs, but there it never did any harm. But now with terraform treating it like a setting, not a state (what is not wrong and also the expected behavior ...), it's resulting in this issue.
### References
Perhaps related issues:
- GH-562
- GH-491

**Comment by bill-rich** [comment]
Hi @thetuxkeeper. Currently, the provider does not allow you to change disk types. The reason is that the steps to implement are more of a process than a setting change. Converting from thin to thick is fairly straight forward (as long as there are no snapshots), but converting from thick to thin requires migration between datastores.

I'll put this request on the backlog, and I will look into the API steps required to implement the enhancement.

**Comment by thetuxkeeper** [comment]
Hi @bill-rich. I think you misunderstood my intention. 
AFAIK the disk type changes in a state-like way (disk full once => not thinprovisioned anymore => changes from thin to thick without any change of the disk itself). So if that is correct (I'm quite sure), then terraform should ignore the setting of the disk except for the time the disk is created. But not trying to change it, since how should terraform know if the disk was created correctly and just has a "wrong" state.

**Comment by bill-rich** [comment]
Thanks @thetuxkeeper. You are correct. I did misunderstand at first. I was not aware that the disk type changes in that way, but that is very good to know. I'll do some testing and try to get this addressed soon.

**Comment by mimmus** [comment]
Any workaround?
I'm currently blocked.

Thanks

**Comment by bill-rich** [comment]
I've looked more into this issue and haven't been able to reproduce the issue. I'd like to check make sure I am following the correct steps to reproduce the issue. I've tried:

1. Create a `vsphere_virtual_machine` with a disk with `thin_provisioned` set to `true`
2. Fill the disks with zeros
3. Run `terraform apply` (still works)
4. Fill disks with ones
5. Run `terraform apply` (still works)

and then 

1. Create a `vsphere_virtual_machine` with a disk with `thin_provisioned` set to `false` and `eagerly_scrub` set to true
2. Fill the disks with zeros
3. Run `terraform apply` (still works)
4. Fill disks with ones
5. Run `terraform apply` (still works)

I tried with both because the error that is reported is actually about `eagerly_scrub` and wanted to make sure I was covering each possibility. I also confirmed with the API docs that `eagerlyScrub` is just a flag to set if the disk should be completely scrubbed at the time of creation, so it doesn't look like that should be changing without some manual VMDK intervention.

If you're running into this problem, you should be able to work around it by setting `eagerly_scrub` to `true` in the `disk` configuration.

**Comment by mimmus** [comment]
I'm not able to replicate but periodically it comes out.

**Comment by thetuxkeeper** [comment]
I found a way to reproduce it! You have to create a snapshot to trigger the change.

**Comment by vkmellon** [comment]
Have similar issue.
In my case i have VMWare template with thin provisioning disk. I want to change disk type on deployment. So I set 
      thin_provisioned = false
      eagerly_scrub    = true

And it is failing with error:
Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: cannot change the value of "thin_provisioned" - (old: true new: false)

**Comment by bill-rich** [comment]
@thetuxkeeper I finally got back to looking at this issue, and although it can be kind of annoying, I actually think Terraform is behaving as expected. Since the disk type is changing on the vSphere side, the Terraform config no longer reflects the VM's actual state. When you run into this problem, I'd recommend adding `eagerly_scrub = true` and `thin_provisioned = false` to your configuration. 

@vkmellon It sounds like what you're looking for is the ability to actually change the disk type through Terraform. That isn't currently supported, but it is on the roadmap for the future.
