### ISSUE TITLE
Default Values for cpu_hot_add_enabled and memory_hot_add_enabled

### ISSUE THREAD

**Issue by luckerby** [terraform-providers/terraform-provider-vsphere#781]
Running on terraform `v0.11.11`. 

After a basic VM clone is performed - including a `terraform apply`, as required in the Note [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#cpu_hot_add_enabled) - based on a machine that has a configuration which allows both CPU and memory hotplug, the resulting VM has both features disabled, as seen below.

![image](https://user-images.githubusercontent.com/31319583/58945660-fa898b00-878c-11e9-98b8-d17e799ac774.png)

Cloning the same VM manually results in the original options kept.

My guess is that the behavior observed through terraform is due to the default values of `cpu_hot_add_enabled` and `memory_hot_add_enabled`, which I suspect is a boolean false. However I can't a reference to the default value in the documentation.

What is the default value of these 2 values ?

**Comment by bill-rich** [comment]
Hi @luckerby! You are correct that `cpu_hot_add_enabled` and `memory_hot_add_enabled` will default to `false`. It isn't entirely clear since it is not explicitly documented, but in Terraform, when a default value is not specified, it is `false` for bools. If you need those options enabled, you should be able to just set them to `true` in your config. Let me know if you run into any problems there!
