### ISSUE TITLE
Vsphere provider Windows VM template - NetFirewall Public Profile keep resetting to True

### ISSUE THREAD

**Issue by orlybagasala** [terraform-providers/terraform-provider-vsphere#791]
Hi there,

I'm trying to provision a Windows VM using our template that has disabled NetFirewallProfile for Domain,Public,Private but after TF build, the NetFirewall profile for Public keeps resetting to True. I also tried to disable it using run_once_command_list but it still being enabled after TF build. This issue is preventing us from running remote-exec commands using winrm. Please advise.

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    customize {
      windows_options {
        computer_name = "${var.vsphere_vm_name}"
        admin_password = "${var.vsphere_win_password}"
        run_once_command_list = [
              "powershell.exe -Command Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False"
        ]
        auto_logon = "true"
        auto_logon_count= "1"

### Terraform Version
0.11.13

**Comment by bill-rich** [comment]
Hi @orlybagasala! The setting of NetFirewallProfile is most likely due to Sysprep being run on the VM during boot. If you're using customize in the VM config, vSphere will use Sysprep to customize the OS. You can work around this by using `windows_sysprep_text` along with a Sysprep answer file (sysprep.inf) to configure the VM as needed.

`run_once_command_list` won't work in this case since it only runs the command once a user has logged in.

**Comment by rismoney** [comment]
If you are using packer, or however you build your template - run this before you shutdown:

https://github.com/gildas/packer-windows/blob/master/scripts/02-fix-network.ps1
