### ISSUE TITLE
dynamic disk in the vsphere_virtual_machine

### ISSUE THREAD

**Issue by skydion** [terraform-providers/terraform-provider-vsphere#832]
Hi there,

I'm trying create a few disk, but get error. So it is the bug of provider or it is my error with config file? I'm trying use **name** instead **label** but get the same error.

### Terraform Version
Terraform v0.12.7
+ provider.null v2.1.2

### vSphere Provider Version
+ provider.vsphere v1.12.0

### Affected Resource(s)
- `vsphere_virtual_machine`

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
locals {
  ds_disk_size  = ["64", "64"]
}

dynamic "disk" {
    for_each = local.ds_disk_size

    content {
      label             = "disk${count.index+1}"
      size              = "${disk.value}"
      thin_provisioned  = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
      unit_number       = "${count.index+1}"
    }
  }
```

### Debug Output
**Error: disk: duplicate name disk2**

  on data_stores.tf line 9, in resource "vsphere_virtual_machine" "ds":
   9: resource "vsphere_virtual_machine" "ds" {

**Error: disk: duplicate name disk1**

  on data_stores.tf line 9, in resource "vsphere_virtual_machine" "ds":
   9: resource "vsphere_virtual_machine" "ds" {

**Comment by bykvaadm** [comment]
They say, that count and for_each doesn't work in current terraform (0.12.x) - see https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each on "Module count and for_each".

So, as u take count, its value comes from upper level, that's why u have multiply same values.

as for me, i changed a little your code and it works.
`
resource "vsphere_virtual_machine" "vm" {
  name             = "${var.prefix}${var.name}-${count.index}"
  count            = "${var.instance_count}" 
...
  dynamic "disk" {
    for_each = [for d in var.disk_size: {
      size   = d.size
      number = d.number
    }]

    content {
      label            = format("disk%s", disk.value.number)
      size             = disk.value.size
      unit_number      = disk.value.number
    }
  }
}
`
and disk size variable:

`variable "disk_size" {
  type    = "list"
  default = [
    {
      size   = 20,
      number = 0
    },
    {
      size   = 300,
      number = 1
    }]
}`

**Comment by skydion** [comment]
Thanks for you reply.

I tried you code and it work, great!

But I don't understand errors which I give previously:
**Error: disk: duplicate name disk2
Error: disk: duplicate name disk1**
As we see the name is different, what mean this errors?

**Comment by bill-rich** [comment]
The errors are a little confusing in this context. What was happening was that both disks on your first VM were using the VM's `count.index`, so both were named `disk1` for the first VM and both were called `disk2` on the second.
