### ISSUE TITLE
customization forces replacement of vm

### ISSUE THREAD

**Issue by uutest74** [terraform-providers/terraform-provider-vsphere#929]
Hi there,

### Terraform Version
Terraform v0.12.16

### vSphere Provider Version
+ provider.vsphere v1.13.0

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

FIRST
generate  vm with 2 network adapters, customization apply ip for first adapter,
and empty for second

```hcl

resource "vsphere_virtual_machine" "test-tf"{
****************************
**********
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }
clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
    ******************
       network_interface {
        ipv4_address = "192.168.0.30"
        ipv4_netmask = 24
      }
      network_interface {
      }    
    *********************************
    }
  }
}
```

SECOND
Now i remove 1 network_interface form customization and 1 network_interface from vm
```hcl
resource "vsphere_virtual_machine" "test-tf"{
****************************
**********
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }
clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    customize {
    ******************
       network_interface {
        ipv4_address = "192.168.0.30"
        ipv4_netmask = 24
      }
    *********************************
    }
  }
}
```
### Expected Behavior

**VM change in place remove network adapter.
Without customize section Terraform do it!!!**

### Actual Behavior

vsphere_virtual_machine.test-tf must be replaced
******************
           ~ network_interface { # forces replacement
                  - dns_server_list = [] -> null
                    ipv4_address    = "192.168.0.30"
                    ipv4_netmask    = 27
                  - ipv6_netmask    = 0 -> null
                }
              - network_interface { # forces replacement}

But with "customize" Terraform  forces replaced of VM and this is not expected behavior!
**Also important!** if i declare two network adapters in vm section and only one in customize (no empty block network_interface { } )     - vmware say:
error sending customization spec: The number of network adapter settings in the customization specification: 1 does not match the number of network adapters present in the virtual machine: 2  - it is really circle of laps!!! 

**Need fix terraform to dont replace vm with customized network adapters**

**Comment by bill-rich** [comment]
Hi @uutest74! Despite it seeming odd in this case, it is actually expected behavior. We want to make sure the configuration reflects the actual state of the virtual machine. Because customization can only be done during cloning, we have made it so that any changes to customization force a new resource.

Even if we changed the behavior of the customization check to allow changes to reduce the number of network interfaces, as long as it matches the number of interfaces in the VM base config, we could still easily get into situations where the configuration and the actual state don't match. For example, if you started with two network interfaces, and removed the 2nd from the base config, and the customization information that was applied to the network interface, you would then be out of sync.
