### ISSUE TITLE
Customization Specifications Manager  (feature request)

### ISSUE THREAD

**Issue by Boran** [terraform-providers/terraform-provider-vsphere#97]
In the vSphere UI one can select a "Customization Specification" when creating a new VM, which defines the network, DNS etc. This is an XML file, see references below.

There does not seem to be any support for this in terraform. 
It is needed for networks with DHCP for example.

### Terraform Version
0.9.8

### References
https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc%2FGUID-C72FA9A6-3871-4838-A4AE-50E218488CD4.html

Another provider implementation that has this implemented?
https://github.com/Banno/terraform-provider-vsphere

**Comment by vancluever** [comment]
Hey @Boran - thanks for the request!

We can definitely add this to the TODO, but I'm wondering if https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#network_interface would do what you need in terms of customizing a VM with just DHCP.

Also - maybe I'm missing something but https://github.com/Banno/terraform-provider-vsphere does not seem to have a specific resource for managing customization specs. The VM resource there allows one to create a VM with the customization spec, but that's all I see.

Thanks!

**Comment by Boran** [comment]
Yes, one can create VMs and get network access with DHCP, without having a customisation spec.

Being able to assign customisation specs when creating new Vms would be a nice feature, since we use it for all VMs we create with the vSphere UI and it would be consistent.

**Comment by PandaXass** [comment]
Hi @vancluever I think this is a very important feature and a lot of vSphere users are relying on the customization specification for creating VMs. :)

**Comment by tdanner01** [comment]
Hi @vancluever, 
I too, am trying to leverage the vCenter 'Customization Spec'. I'm attempting this on a Windows Guest OS after spinning a VM from a template. The objective is to customize using an existing customization specification to do the following:
Apply a proper Windows License - 'Product Key' and 'Set the Licensing Mode'
Set the local Administrator pw
Add the VM's Guest OS (Windows Host) to a Domain (by passing proper creds)
Gen a new SID for the Guest OS

I tried the following at the end of the build.tf:

# Define the Customization Specification
    custom_configuration_parameters = {
        spec = "W2k12R2Standard-VC2"
    } 

Is the syntax correct? 
Is this in the provider yet?
Is there another way that I can try to accomplish this?

**Comment by vancluever** [comment]
Hey @tdanner01, #244 is going in soon which makes big improvements to customization experience. Check the pending [documentation update](https://github.com/terraform-providers/terraform-provider-vsphere/blob/f-vm-resource-refactor/website/docs/r/virtual_machine.html.markdown) for more information. All the information for Windows customization should be there as well.

One note though in regards to your licensing mode question - just checking why we didn't include that, and it looks like that it's essentially a deprecated option for Windows Server 2003 or lower, which has been EOL for a few years now and as a result we are not supporting. I'm guessing all you should need to do is supply the product key. All of the other options you have mentioned should be there though.

Thanks!

**Comment by tdanner01** [comment]
Thank you @vancluever. I started reading up on the improvements. Looking forward to the version.

**Comment by vancluever** [comment]
Hey all,

I know this is a dormant issue and there has been a lot of changes since the last discussion on this topic last fall. Since the release of 1.0 added a much more complete customization specification to the `vsphere_virtual_machine` resource, I'm now thinking that this is not necessary - in addition to the fact that it might not be a 100% good fit for Terraform.

Customization specifications in the vSphere client, from what I remember, can be incomplete in certain ways that allow fields can be filled in during customization. In order to preserve the UX that we have, and provide some level of usefulness, what would probably be the data source would have to be able to accept some incomplete options that would need to be customized later. This would make this what would be simple UX relatively complicated:

```
data "vsphere_customization_specification" "spec" {
  name = "W2k12R2Standard-VC2"
}

resource "vsphere_virtual_machine" "vm" {
  ...

  clone {
    ...
    customize = "${data.vsphere_customization_specification.spec.data}"
  }
}
```

Considering this, and that the new, declarative nature of the customization specification provides a way that supply and paramterize customization settings that are much more in line with how Terraform is intended to be used, I think it's probably better to not implement this, favouring instead the existing functionality.

For those who haven't really followed the new VM resource since the provider revamp last year, please see [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#virtual-machine-customization) for full details on how VM customization now works.

Thanks!

**Comment by AndrewCi** [comment]
I agree with you in a spirit but not necessarily in practice. I do believe a workaround should be considered for users who have existing customization specs populated into vSphere. Or at least a way to import existing specs configured through the vSphere Custom Spec Manager.

**Comment by roiems** [comment]
Any updates on this ?

**Comment by dfoley84** [comment]
Can we please get a work around for people with "Use Cases" that have Custom Specs within their vSphere Environmnet.
