### ISSUE TITLE
Extension of rest client specific to tags and content library

### ISSUE THREAD

**Issue by shylasrinivas** [terraform-providers/terraform-provider-vsphere#998]
The rest client in config.go https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/config.go#L365 is specific to tags and content library.

Can this be extended to other URLs like rest/vcenter? In addition to the existing rest client, can a new rest client object be added in the vSphereClient struct? Is there a recommended approach?
https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/config.go#L33

**Comment by shylasrinivas** [comment]
To provide more context, we are trying to add compute policy feature support and the url for these APIs is /rest/vcenter/compute/policies.

**Comment by shylasrinivas** [comment]
Also want to add that vLCM (life cycle management) apis are on a different url - https://{server}/api/esx/
I am looking for ideas on how to make the rest client generic enough to handle different urls and if this is something you have already thought of. Appreciate your response!

**Comment by bill-rich** [comment]
Hi @shylasrinivas!

Although there are several strategies we could use to extend support to other URLs, I think a better approach would be to wait for official support in either govmomi or another SDK. 

The current implementation is a workaround so that we could roll out support for a couple of REST based features, but I would like to avoid continuing to develop and rely on the workaround for future work. 

If you're looking to further utilize these features, I'd recommend taking the work that has been done on the Terraform provider side and work on getting them ported over to the govmomi side. Ideally, the session reuse code could be reconfigured to support different URLs so that it would be possible to use one client for all REST-based functions.
